// AI in China - Posts Metadata
// 文章元数据管理文件
// ⚠️ AUTO-GENERATED by scripts/sync-metadata.js — DO NOT EDIT MANUALLY
// Generated: 2026-08-23T20:24:22.600Z

const allPosts = [
  {
    slug: 'china-ai-profit-pivot-skeptics-wrong-2026',
    title: "The $300 Million Answer: How China's AI Industry Just Proved It Can Make Money",
    category: "AI Business",
    excerpt: "For two years, Western analysts predicted China's AI companies would collapse under unsustainable burn rates. Then August 2026 happened. MiniMax doubled ARR to $300 million in 60 days. DeepSeek hit $74 billion valuation. The industry-wide price war ended with synchronized price increases. The burn rate narrative was wrong — and the numbers prove it.",
    date: '2026-08-24',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=1200&q=80"
  },
  {
    slug: 'china-green-ai-computing-inner-mongolia-sustainable-intelligence-2026',
    title: "China's Green AI Computing Revolution: How Inner Mongolia Built the World's Largest Sustainable Intelligence Factory",
    category: "AI",
    excerpt: "At the 2026 Green Computing Power Conference in Hohhot, China signed ¥186 billion in green AI infrastructure projects. Inner Mongolia now hosts 315,000 petaflops of computing power—one-seventh of China's total—powered by 84% renewable energy. The rest of the world is still debating AI's carbon footprint. China has already solved it at scale.",
    date: '2026-08-23',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=1200&q=80"
  },
  {
    slug: 'china-open-source-trap-ai-strategy-silicon-valley-2026',
    title: "The Open-Source Trap: How China's AI Strategy Is Making Closed Models Obsolete",
    category: "'Industry'",
    excerpt: "The dominant narrative about China's artificial intelligence industry has remained stubbornly consistent for the better part of a decade: China copies, America innovates. Chinese tech firms, the...",
    date: '2026-08-23',
    readTime: '15 min read',
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&h=400&fit=crop"
  },
  {
    slug: 'china-ai-token-price-war-end-pricing-reset-2026',
    title: "China's AI Token Price War Is Over: Why the Industry-Wide Pricing Reset Signals Global AI Maturity",
    category: "AI Business",
    excerpt: "DeepSeek's August 17 peak-valley pricing implementation marked the formal end of China's two-year AI token price war. With Zhipu, Moonshot, Tencent, and cloud providers all raising prices, the industry is entering a sustainable pricing era that mirrors global software economics.",
    date: '2026-08-22',
    readTime: '16 min',
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&q=80"
  },
  {
    slug: 'china-embodied-ai-robotics-revolution-2026',
    title: "The Physical AI Revolution: How China Is Winning the Race for Embodied Intelligence",
    category: "AI Robotics",
    excerpt: "While Silicon Valley obsesses over chatbots, China is building an army of thinking machines that can walk, drive, and manipulate the physical world. From DeepSeek's robotics debut to Unitree's $9 billion IPO, embodied AI has become China's most consequential AI frontier.",
    date: '2026-08-22',
    readTime: '17 min',
    image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=1200"
  },
  {
    slug: 'bytedance-10-trillion-parameter-model-china-ai-scale-bet-2026',
    title: "ByteDance's 10 Trillion Parameter Gamble: Why the Biggest Number in AI Might Not Mean What You Think",
    category: "AI Business",
    excerpt: "ByteDance is pre-training a 10-trillion-parameter AI model that would dwarf every Chinese competitor and rival Anthropic's Mythos 5. But in the Mixture-of-Experts era, total parameters measure storage capacity—not intelligence. The real story lies in what ByteDance isn't saying.",
    date: '2026-08-21',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200&q=80"
  },
  {
    slug: 'huawei-ascend-950dt-cloud-launch-china-ai-training-sovereignty-2026',
    title: "From Entity List to Cloud Launch: How Huawei's Ascend 950DT Closed the Loop on China's AI Training Sovereignty",
    category: "Semiconductors",
    excerpt: "On August 20, 2026, Huawei's Ascend 950DT training chip went live on Huawei Cloud — the culmination of a six-year journey from US sanctions to self-sufficiency. With 144GB of in-house HBM, 4 TB/s bandwidth, and DeepSeek V4 already proven on the architecture, China now has an end-to-end domestic training stack. The per-chip gap to Nvidia remains large. But the system-level bet is paying off.",
    date: '2026-08-21',
    readTime: '15 min',
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&q=80"
  },
  {
    slug: 'bytedance-10-trillion-parameter-model-china-ai-scaling-race-2026',
    title: "ByteDance's 10-Trillion-Parameter Bet: How China's Biggest AI Model Is Rewriting the Scaling Race",
    category: "AI Business",
    excerpt: "ByteDance is reportedly pre-training a 10-trillion-parameter AI model — triple the size of any Chinese model shipped and rivaling Anthropic's Mythos 5. Behind the number lies a deeper shift: a no-distillation policy, a $5.6 billion Huawei chip order, and a founder mandate to chase world-class capability over short-term wins.",
    date: '2026-08-20',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&h=400&fit=crop"
  },
  {
    slug: 'zhipu-glm-5-3-post-training-coding-cyber-revolution-2026',
    title: "Zhipu GLM-5.3: How 30 Days of Post-Training Turned a 743B Model Into China's Coding King",
    category: "AI Business",
    excerpt: "On August 14, 2026, Zhipu AI released GLM-5.3 with a radical claim: every capability gain came from post-training, not a new pretraining run. The 743B-parameter model leaped 515% on Terminal-Bench 3.0, discovered 2,436 vulnerabilities in open-source code, and forced a conversation about whether the AI frontier has shifted from scale to training strategy.",
    date: '2026-08-20',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=1200&q=80"
  },
  {
    slug: 'china-ai-trinity-glm-deepseek-kimi-2026',
    title: "China's AI Trinity: GLM-5.3, DeepSeek V4, and Kimi K3 — A Comparative Framework",
    category: "AI Development",
    excerpt: "In mid-August 2026, three Chinese AI labs dropped flagship models within one week. We compare GLM-5.3, DeepSeek V4-Pro, and Kimi K3 across architecture, pricing, benchmarks, and strategy to reveal what China's AI trinity means for the global open-source race.",
    date: '2026-08-19',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&h=400&fit=crop"
  },
  {
    slug: 'china-open-source-ai-3-billion-downloads-qwen-deepseek-2026',
    title: "3 Billion Downloads and Counting: The Great Open Source Reversal Nobody in Silicon Valley Saw Coming",
    category: "Global AI Competition",
    excerpt: "Alibaba's Qwen just crossed 3 billion global downloads, surpassing Meta's Llama and Google's entire model family. DeepSeek Harness hit 141,000 GitHub stars in four days. Kimi K3 became the world's largest open-weight model at 2.8 trillion parameters. The open-source AI narrative has been rewritten — and this time, the byline is Chinese.",
    date: '2026-08-19',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&q=80"
  },
  {
    slug: 'world-humanoid-robot-games-beijing-2026',
    title: "2,056 Robots, 666 Teams, One Arena: Inside the World's Largest Humanoid Robot Games",
    category: "AI",
    excerpt: "The second World Humanoid Robot Games opens August 22 in Beijing's Ice Ribbon with 2,056 robots from 16 countries competing across 51 events. Here's why this event matters more than entertainment—it's become the proving ground for China's embodied AI ambitions.",
    date: '2026-08-18',
    readTime: '15 min read',
    image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=1200&q=80"
  },
  {
    slug: 'bytedance-ai-strategic-pivot-admit-weakness-play-strengths-2026',
    title: "ByteDance Just Admitted Its AI Is Behind. That's Exactly Why It's Winning.",
    category: "AI Strategy",
    excerpt: "On August 6, 2026, ByteDance CEO Liang Rubo did something no Chinese tech leader had dared: he told 110,000 employees that his company's large language models lag behind America's. The confession was not surrender. It was the opening move of a strategy that may prove more durable than any parameter-count arms race.",
    date: '2026-08-17',
    readTime: '16 min',
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200"
  },
  {
    slug: 'china-ai-medical-insurance-global-first-2026',
    title: "The 1.2 Billion Patient Experiment: How China Put AI Doctors on National Insurance",
    category: "Healthcare AI",
    excerpt: "On April 1, 2026, China became the first nation to reimburse AI-assisted diagnoses through national health insurance. Eight hundred thirty-seven top hospitals now bill insurers for AI readings of CT scans, retinal images, and ECGs—with patients paying as little as 15% out of pocket.",
    date: '2026-08-17',
    readTime: '16 min',
    image: "https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=1200"
  },
  {
    slug: 'unitree-610-billion-ipo-china-robot-capital-markets-2026',
    title: "The $85 Billion Robot: How Unitree's Historic IPO Proves China's AI Manufacturing Dominance",
    category: "AI Robotics",
    excerpt: "For three years, the consensus among Western analysts was brutally simple: Chinese robotics companies were burning venture capital on science projects. The humanoid robots looked impressive in demo...",
    date: '2026-08-17',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=1200"
  },
  {
    slug: 'facewall-intelligence-ipo-edge-ai-china-first-llm-listing-2026',
    title: "FaceWall Intelligence's $3 Billion IPO Gambit: Can China's Edge AI Pioneer Rewrite the Rules of Public Markets?",
    category: "AI",
    excerpt: "On the morning of August 11, 2026, a regulatory filing appeared on the China Securities Regulatory Commission's disclosure platform. It contained no press release, no celebratory announcement. Just...",
    date: '2026-08-16',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1594915440248-1e419eba6611?w=1200"
  },
  {
    slug: 'minimax-h3-open-source-video-model-china-2026',
    title: "MiniMax H3: The 33-Billion-Parameter Video Model That China Just Gave Away",
    category: "AI",
    excerpt: "MiniMax open-sourced H3, a 33B omni-modal video model capable of 2K generation with native stereo audio. Within 48 hours, the global community built LoRA support and Apple Silicon inference. Here's what this means for the future of open-source video generation.",
    date: '2026-08-15',
    readTime: '12 min read',
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&h=400&fit=crop"
  },
  {
    slug: 'china-nvidia-h200-reversal-huawei-ascend-paradox-2026',
    title: "The Great Silicon Reversal: Why Beijing Is Quietly Letting Its AI Giants Buy Nvidia Again",
    category: "Semiconductors",
    excerpt: "After spending eighteen months and hundreds of billions of yuan building a Nvidia-free AI chip ecosystem around Huawei Ascend, Beijing is now allowing ByteDance, Alibaba, Tencent and DeepSeek to purchase limited quantities of Nvidia H200 chips. The reversal reveals a strategic fracture that nobody saw coming.",
    date: '2026-08-14',
    readTime: '16 min',
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&q=80"
  },
  {
    slug: 'us-sanctions-built-china-ai-chip-industry-cambricon-smic-2026',
    title: "How US Sanctions Built China's AI Chip Industry: The Cambricon Miracle and the SMIC Bottleneck",
    category: "AI",
    excerpt: "Cambricon just posted its first annual profit after nine years of losses, with revenue surging 453%. The company it should thank? NVIDIA — or rather, the US government that banned NVIDIA from selling to China. Inside the great semiconductor irony of 2026.",
    date: '2026-08-14',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200"
  },
  {
    slug: 'baichuan-ai-healthcare-pivot-wang-xiaochuan-medical-ai-2026',
    title: "Sole Survivor: How Wang Xiaochuan Burned Down China's 'OpenAI' to Build an AI Doctor",
    category: "Healthcare AI",
    excerpt: "In March 2025, Wang Xiaochuan made a decision no Chinese AI founder had dared: he killed his own general-purpose model, fired his entire co-founding team, and bet everything on medical AI. Eighteen months later, Baichuan-M4 ranks #1 globally on HealthBench, serves 500,000 paying users, and has a clearer path to profit than any 'Six Little Dragon' peer.",
    date: '2026-08-13',
    readTime: '16 min',
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1200&q=80"
  },
  {
    slug: 'deepseek-price-war-end-8-billion-robotics-pivot-2026',
    title: "DeepSeek Ends the Price War: Why China's AI Unicorn Is Raising Prices, Raising $8 Billion, and Betting on Robots",
    category: "Artificial Intelligence",
    excerpt: "On August 6, 2026, DeepSeek did what no one thought possible: it raised prices. After processing 8 trillion tokens in a single day, the Hangzhou lab announced a funding round at $74 billion and a strategic robotics partnership with Unitree. The era of China's AI price war is ending — and something far more interesting is beginning.",
    date: '2026-08-12',
    readTime: '17 min',
    image: "https://images.unsplash.com/photo-1676299081847-824916de030a?w=1200&q=80"
  },
  {
    slug: 'kimi-k3-open-source-trillion-parameter-china-ai-2026',
    title: "Kimi K3: The 3-Trillion-Parameter Open-Source Moonshot That Broke the Internet",
    category: "AI",
    excerpt: "It was supposed to be a routine product launch. On July 16, 2026, Moonshot AI — the Beijing-based startup behind the Kimi chatbot — unveiled its most ambitious creation yet: Kimi K3, a model with 2.8...",
    date: '2026-08-12',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1523961131990-5ea7c61b2107?w=1200&q=80"
  },
  {
    slug: 'china-ai-openrouter-revolution-global-api-dominance-2026',
    title: "The OpenRouter Revolution: How Chinese AI Models Captured Two-Thirds of Global API Traffic",
    category: "Global AI Competition",
    excerpt: "On August 2, 2026, OpenRouter's weekly rankings revealed something Silicon Valley refused to believe: the top five most-called AI models on Earth were all Chinese. From DeepSeek's $0.87-per-million-token API to Xiaomi's MiMo-V2.5 surging 616% in sixty days, Chinese models now command 63.5% of global API traffic — and the infrastructure map of AI has been redrawn.",
    date: '2026-08-11',
    readTime: '16 min',
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200"
  },
  {
    slug: 'apple-intelligence-china-qwen-baidu-ai-sovereignty-2026',
    title: "Two Apple Intelligences: How China's Regulatory Approval Forced Apple to Rebuild Its AI From the Inside",
    category: "AI Policy",
    excerpt: "Apple Intelligence finally cleared China's regulatory hurdle on July 15, 2026 — but the version Chinese iPhone users will receive is architecturally different from what runs everywhere else. Here's what the Qwen-Baidu partnership reveals about the future of AI sovereignty.",
    date: '2026-08-10',
    readTime: '16 min',
    image: "https://images.unsplash.com/photo-1523961131990-5ea7c61b2107?w=1200&h=600&fit=crop"
  },
  {
    slug: 'deepseek-v4-flash-0731-post-training-beats-scale-2026',
    title: "DeepSeek V4-Flash-0731: The Post-Training Breakthrough That Beat Its Own 1.6 Trillion-Parameter Flagship",
    category: "AI Models",
    excerpt: "On July 31, 2026, DeepSeek released V4-Flash-0731 — the same 284 billion-parameter model, re-post-trained on agent data. It beat its own 1.6 trillion-parameter V4-Pro-Preview on every agent benchmark. At $0.14 per million tokens, it is the cheapest capable agentic model on Earth. The implication is radical: scale is no longer the primary frontier.",
    date: '2026-08-10',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1639322537228-f710d846310a?w=1200"
  },
  {
    slug: 'china-ai-model-wars-summer-2026',
    title: "China's AI Model Wars: The Summer That Changed Global AI",
    category: "AI Industry",
    excerpt: "In the span of four months, four Chinese AI labs—Moonshot, DeepSeek, ByteDance, and Alibaba—released models that collectively erased the perceived capability gap between Chinese and American AI. With 2.8 trillion-parameter open weights, 1.6 trillion-parameter MoE architectures, and a 10 trillion-parameter behemoth in training, China's AI model ecosystem has gone from follower to co-leader.",
    date: '2026-08-09',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=1200&q=80"
  },
  {
    slug: 'bytedance-seedance-2.5-ai-video-revolution-2026',
    title: "Seedance 2.5: How ByteDance Built the World's Most Ambitious AI Video Engine",
    category: "AI Video & Creative",
    excerpt: "ByteDance's Seedance 2.5 delivers native 4K video, 30-second single-generation clips, and 50 simultaneous reference inputs. Launched in July 2026, it represents not merely a product upgrade but a declaration that China intends to own the creative AI layer — from TikTok's billion users to Hollywood's post-production pipelines.",
    date: '2026-08-08',
    readTime: '17 min',
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200&q=80"
  },
  {
    slug: 'openai-price-war-chinese-ai-rivals-2026',
    title: "OpenAI Blinks: How an 80% Price Cut Revealed the New Power Balance in Global AI",
    category: "Global AI Competition",
    excerpt: "In August 2026, OpenAI slashed GPT-5.6 prices by up to 80% — not to reward developers, but to stop the bleeding. DeepSeek V4-Flash had already claimed the top spot on OpenRouter. Chinese models occupied nine of the global top ten. For the first time, an American frontier lab was fighting a price war it did not start.",
    date: '2026-08-08',
    readTime: '16 min',
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=1200"
  },
  {
    slug: 'china-ai-monetization-awakening-end-free-token-era-2026',
    title: "China's AI Monetization Awakening: How the Industry Killed 8 Million Free Bots to Build a Real Business",
    category: "AI Business",
    excerpt: "Liu wasn't alone. Across China, eight million user-created AI agents — virtual companions, coding assistants, study tutors, fantasy characters, and business automation bots — went dark within a...",
    date: '2026-08-07',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=600&fit=crop"
  },
  {
    slug: 'tencent-hy3-ai-turnaround-openrouter-china-2026',
    title: "How Tencent's Hy3 Turned the Tables on China's AI Wars",
    category: "AI",
    excerpt: "Tencent's Hunyuan Hy3 model went from industry laughingstock to OpenRouter's #1 ranked model in three months. Inside the organizational shakeup, the 28-year-old prodigy, and the engineering philosophy that made it possible.",
    date: '2026-08-07',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=1200"
  },
  {
    slug: 'alibaba-qwen-3-8-max-2-4-trillion-china-ai-race-2026',
    title: "Alibaba's Qwen 3.8-Max: The 2.4 Trillion-Parameter Gamble That Just Reset China's AI Race",
    category: "AI Business",
    excerpt: "On August 3, 2026, Alibaba released Qwen 3.8-Max: a 2.4-trillion-parameter multimodal model priced at $2 per million input tokens, with open weights promised within days. It is the capstone of a summer that saw four Chinese frontier models drop in six weeks—and a direct challenge to Anthropic's Fable 5 dominance.",
    date: '2026-08-06',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&q=80"
  },
  {
    slug: 'china-embodied-ai-revolution-shenzhen-not-silicon-valley-2026',
    title: "China's Embodied AI Revolution: Why the World Is Building Robots in Shenzhen, Not Silicon Valley",
    category: "Embodied AI",
    excerpt: "China commands 78% of the global humanoid robot market, with 22 unicorns and $13.8B in 2026 funding. The real story isn't hardware—it's an ecosystem Silicon Valley can't replicate.",
    date: '2026-08-06',
    readTime: '16 min',
    image: "https://images.unsplash.com/photo-1523961131990-5ea7c61b2107?w=1200&h=600&fit=crop"
  },
  {
    slug: 'bytedance-fullstack-ai-seedance-audio-doubao-ecosystem-2026',
    title: "ByteDance's Full-Stack AI Gambit: How Seedance 2.5, Seed Audio, and the Doubao Ecosystem Are Reshaping Creative AI in China",
    category: "AI Applications",
    excerpt: "If you have been watching ByteDance's AI strategy from the outside, the past six weeks have felt like watching someone assemble a jigsaw puzzle at triple speed. Pieces that seemed scattered — a video...",
    date: '2026-08-05',
    readTime: '15 min read',
    image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=1200&q=80"
  },
  {
    slug: 'china-ai-open-source-captured-american-developers-2026',
    title: "The Open-Source Reversal: How Chinese AI Models Captured the American Developer",
    category: "Global AI Competition",
    excerpt: "In July 2026, Mozilla's CTO switched to Kimi K3. Coinbase moved workloads to DeepSeek. The top five models on OpenRouter were Chinese. After years of US dominance, a quiet revolution is underway — and it's being built on open weights, radical affordability, and engineering excellence.",
    date: '2026-08-05',
    readTime: '16 min',
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200"
  },
  {
    slug: 'baidu-kunlunxin-50-billion-ipo-china-ai-chip-independence-2026',
    title: "The $50 Billion Silicon Gamble: Inside Baidu's Kunlunxin IPO and China's Race for AI Chip Independence",
    category: "AI Infrastructure",
    excerpt: "On the morning of June 28, 2026, a story hit The Information that sent shockwaves through both Silicon Valley and Zhongguancun. Baidu's AI chip subsidiary, Kunlunxin, was targeting a Hong Kong IPO...",
    date: '2026-08-04',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&q=80"
  },
  {
    slug: 'china-ai-six-tigers-divergence-ipo-wave-2026',
    title: "The Six Tigers No More: How China's AI Unicorns Split Into Six Different Species",
    category: "AI Business",
    excerpt: "China's 'Six AI Tigers' were once treated as a single class of company. In 2026, they've become six entirely different species — with $100 billion valuations, healthcare pivots, enterprise retreats, and hardware bets that share nothing but a founding year.",
    date: '2026-08-03',
    readTime: '16 min',
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=1200"
  },
  {
    slug: 'china-embodied-intelligence-revolution-brains-beat-bodies-2026',
    title: "China's Embodied Intelligence Revolution: Why 2026 Is the Year Brains Finally Beat Bodies",
    category: "AI Industry",
    excerpt: "China's embodied intelligence sector raised 934.7 billion RMB in H1 2026, surpassing all of 2025. But the real story isn't the funding numbers—it's the shift from 'PPT robots' to commercial contracts, from hardware demos to model-driven productivity.",
    date: '2026-08-02',
    readTime: '16 min',
    image: "https://images.unsplash.com/photo-1523961131990-5ea7c61b2107?w=1200"
  },
  {
    slug: 'huawei-atlas-950-superpod-china-ai-chip-independence-2026',
    title: "The Atlas Gambit: How Huawei's 8,192-Chip SuperPoD Is Rewiring the Global AI Hardware Order",
    category: "Semiconductor & Infrastructure",
    excerpt: "At WAIC 2026, Huawei unveiled the Atlas 950 SuperPoD — an 8,192-chip system claiming 6.7x the compute of Nvidia's NVL144. With DeepSeek V4 running on Huawei silicon, ByteDance committing $5.6 billion, and Beijing declaring computing a national utility, China's AI hardware decoupling has reached its tipping point.",
    date: '2026-08-01',
    readTime: '16 min',
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200"
  },
  {
    slug: 'apple-intelligence-china-alibaba-baidu-real-winners-2026',
    title: "Apple Intelligence in China: Why Alibaba and Baidu Are the Real Winners",
    category: "AI Policy",
    excerpt: "Apple finally got its AI approved in China through partnerships with Alibaba and Baidu. But the deal reveals something far more significant: Chinese AI has already won.",
    date: '2026-07-31',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=1200"
  },
  {
    slug: 'moonshot-kimi-k3-2-8-trillion-open-ai-china-2026',
    title: "Moonshot's Kimi K3: How a 2.8-Trillion-Parameter Open-Weight Model Shook Global Markets",
    category: "AI Models",
    excerpt: "Moonshot AI's Kimi K3 became the world's largest open-weight AI model at 2.8 trillion parameters, triggering a Nasdaq selloff and a White House investigation — all within 48 hours of launch.",
    date: '2026-07-30',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1523961131990-5ea7c61b2107?w=1200"
  },
  {
    slug: 'china-ai-video-models-conquer-global-market-kling-seedance-wan-2026',
    title: "Sora Is Dead, Long Live Kling: How Chinese AI Video Models Conquered Hollywood's Dream Machine",
    category: "Artificial Intelligence",
    excerpt: "OpenAI shut down Sora. In its place, Chinese video models now hold 7 of the top 8 spots globally. From Kling's $500M ARR to Seedance's $2B enterprise empire and Wan 2.7's open-source revolution, the AI video crown has moved east — permanently.",
    date: '2026-07-29',
    readTime: '15 min read',
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200&q=80"
  },
  {
    slug: 'china-open-weight-coding-models-global-software-development-2026',
    title: "The $18 Coding Revolution: How Chinese Open-Weight Models Are Rewriting the Global Software Playbook",
    category: "Artificial Intelligence",
    excerpt: "Chinese open-weight coding models now match 85-90% of frontier performance at 5-10x lower cost. From GLM-5.2's $18 monthly plan to DeepSeek V4's sub-dollar API rates, a new playbook for software development is emerging — and Silicon Valley's closed-source incumbents are being forced to respond.",
    date: '2026-07-28',
    readTime: '14 min read',
    image: "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=1200&q=80"
  },
  {
    slug: 'deepseek-funding-frenzy-74-billion-ipo-china-ai-2026',
    title: "From $0 to $74 Billion in 90 Days: The DeepSeek Funding Frenzy Rewriting China's AI Order",
    category: "Artificial Intelligence",
    excerpt: "DeepSeek went from a hedge fund side project to a $74 billion IPO candidate in 90 days. Here's how China's AI industry learned to print money — and why Silicon Valley is suddenly playing catch-up on capital efficiency.",
    date: '2026-07-27',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?w=1200&q=80"
  },
  {
    slug: 'kimi-k3-moonshot-2-8-trillion-open-weight-model-2026',
    title: "Kimi K3: The 2.8 Trillion-Parameter Open-Weight Model That Moved the Nasdaq",
    category: "Artificial Intelligence",
    excerpt: "Moonshot AI's Kimi K3 became the largest open-source model ever released at 2.8 trillion parameters. Launched at WAIC 2026, it triggered a Nasdaq selloff and proved Chinese AI labs can ship frontier capability as a free download.",
    date: '2026-07-26',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200"
  },
  {
    slug: 'china-ai-compute-crunch-custom-chips-silicon-wall-2026',
    title: "The Silicon Wall: How China's AI Revolution Ran Out of Chips — And Started Building Its Own",
    category: "AI Industry",
    excerpt: "At 3:14 AM on July 19, 2026, Moonshot AI made a decision no fast-growing startup wants to make: it stopped selling. Kimi K3 had grown too popular, too fast. The story of what happened next reveals the hidden battle that will shape the future of global AI.",
    date: '2026-07-25',
    readTime: '22 min read',
    image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&h=600&fit=crop"
  },
  {
    slug: 'china-ai-companion-ban-doubao-qwen-yuanbao-july-2026',
    title: "China Just Unplugged 345 Million Virtual Lovers: Inside the World's First AI Companion Ban",
    category: "AI",
    excerpt: "China Just Unplugged 345 Million Virtual Lovers: Inside the World's First AI Companion Ban On July 15, 2026, Beijing flipped a switch and millions of...",
    date: '2026-07-24',
    readTime: '21 min read',
    image: "https://images.unsplash.com/photo-1639322537228-f710d846310a?w=1200&h=600&fit=crop"
  },
  {
    slug: 'apple-intelligence-china-qwen-baidu-ai-approval-2026',
    title: "The Two-Year Wait Is Over: How Apple Intelligence Cracked China's AI Wall",
    category: "AI Industry",
    excerpt: "After two years of regulatory limbo, Apple Intelligence finally won approval in China through an unprecedented partnership with Alibaba's Qwen and Baidu. Here's what it means for the global AI order.",
    date: '2026-07-23',
    readTime: '16 min',
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200&h=600&fit=crop"
  },
  {
    slug: 'china-ai-july-tipping-point-chips-models-capital-2026',
    title: "The July Tipping Point: How China's AI Industry Crossed the Threshold From Catching Up to Setting the Pace",
    category: "AI Hardware",
    excerpt: "The July Tipping Point: How China's AI Industry Crossed the Threshold From Catching Up to Setting the Pace At 2:47 AM Beijing time on July 17, 2026, a...",
    date: '2026-07-22',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200"
  },
  {
    slug: 'kimi-k3-moonshot-28-trillion-open-ai-2026',
    title: "The 2.8-Trillion Parameter Gambit: How Moonshot's Kimi K3 Is Rewriting the Rules of Open AI",
    category: "AI Models",
    excerpt: "Moonshot AI's Kimi K3 delivers 2.8 trillion parameters with open weights, challenging the closed-source dominance of GPT-5.6 and Claude Fable 5 while proving China's open-source AI strategy is no longer just viable — it's winning.",
    date: '2026-07-21',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=1200&h=600&fit=crop"
  },
  {
    slug: 'waic-2026-live-china-ai-ships-products-humanoid-robot-mass-production',
    title: "WAIC 2026 Live: When China's AI Industry Stopped Competing on Parameters and Started Shipping Products",
    category: "AI Robotics",
    excerpt: "At the 2026 World AI Conference in Shanghai, 1,100 companies showcased 3,000 exhibits across 100,000 square meters. But the real story wasn't the numbers. It was the moment China's AI industry stopped chasing benchmark scores and started shipping products that work.",
    date: '2026-07-20',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=1200&h=600&fit=crop"
  },
  {
    slug: 'chinese-ai-models-46-percent-us-enterprise-invasion-2026',
    title: "The 46% Invasion: How Chinese AI Models Quietly Conquered American Enterprise",
    category: "AI Industry",
    excerpt: "OpenRouter data reveals a shocking reversal: US enterprises now route 46% of their AI model calls to Chinese systems like DeepSeek, Zhipu GLM, and Qwen. At WAIC 2026 in Shanghai, the industry is celebrating a victory that Washington never saw coming.",
    date: '2026-07-19',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80"
  },
  {
    slug: 'apple-intelligence-qwen-china-regulatory-approval-2026',
    title: "Apple Intelligence Clears China: How the Qwen Partnership and a 22-Month Regulatory Marathon Reshaped Global AI's Borderlines",
    category: "AI Industry",
    excerpt: "\"Apple Intelligence Clears China: How the Qwen Partnership and a 22-Month Regulatory Marathon Reshaped Global AI's Borderlines",
    date: '2026-07-18',
    readTime: '24 min read',
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&h=400&fit=crop"
  },
  {
    slug: 'china-embodied-ai-13-billion-funding-boom-2026',
    title: "The $13.8 Billion Awakening: China's Embodied AI Sector Hits Escape Velocity",
    category: "AI Industry",
    excerpt: "In the first half of 2026, China's embodied AI sector attracted $13.8 billion across 322 deals—a fivefold increase from a year ago. With Unitree Robotics clearing its STAR Market IPO in a record 104 days, Momenta listing as the 'physical AI first stock' at 414x oversubscription, and 22 unicorns now roaming the landscape, China's robotics industry has shifted from laboratory curiosity to capital market heavyweight.",
    date: '2026-07-17',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1523961131990-5ea7c61b2107?w=1200&h=600&fit=crop"
  },
  {
    slug: 'kimi-k3-moonshot-2-5-trillion-open-source-ai-2026',
    title: "Kimi K3 and the 2.5 Trillion-Parameter Question: What Moonshot's Leap Means for the Open-Source AI Race",
    category: "AI Chatbots",
    excerpt: "The economics of context — not parameters — will define the next phase of AI competition On July 14, 2026, a promotional page on the Kimi Open Platform...",
    date: '2026-07-17',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=1200&h=600&fit=crop"
  },
  {
    slug: 'china-ai-price-revolution-silicon-valley-waic-2026',
    title: "The $0.07 Model: How China's AI Price Revolution Is Forcing Silicon Valley to Rethink Everything",
    category: "AI Industry",
    excerpt: "In July 2026, a Chinese AI model costs $0.07 per million tokens while its Western equivalent charges $1.25. Goldman Sachs is recommending Chinese models to Wall Street clients. And President Xi Jinping is about to walk into the World AI Conference in Shanghai. This is not a market trend. It is a structural inversion of the global AI order.",
    date: '2026-07-16',
    readTime: '18 min read',
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200&q=80"
  },
  {
    slug: 'china-ai-agent-wars-tencent-alibaba-bytedance-2026',
    title: "The Agent Wars: How Tencent, Alibaba, and ByteDance Are Fighting for China's AI Future",
    category: "AI Industry",
    excerpt: "In mid-2026, China's tech giants have stopped competing on model parameters and started a far more consequential battle: who controls the AI agents that will run the next billion digital tasks. Inside the trillion-yuan race between Tencent's WeChat-integrated WorkBuddy, Alibaba's consolidated QoderWork platform, and ByteDance's Doubao empire.",
    date: '2026-07-15',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1200&q=80"
  },
  {
    slug: 'china-ai-midyear-reckoning-three-forces-2026',
    title: "China's AI Midyear Reckoning: Three Converging Forces Reshaping the Global Technology Order",
    category: "AI Applications",
    excerpt: "On July 15, 2026, China's consumer AI agent ecosystem faces its most consequential regulatory reset yet. Simultaneously, Huawei Ascend chips capture over half the domestic AI chip market, and Chinese humanoid robot exports surge 210%. These are not isolated events. They are the three faces of a single strategic pivot.",
    date: '2026-07-14',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1200"
  },
  {
    slug: 'meituan-longcat-2-trillion-domestic-chips-china-ai-independence-2026',
    title: "How Meituan Built a Trillion-Parameter AI Model on 50,000 Domestic Chips — And Open-Sourced It",
    category: "AI Hardware",
    excerpt: "Meituan's LongCat-2.0 is the world's first trillion-parameter model trained entirely on domestic Chinese chips. Here's why that matters for the global AI race.",
    date: '2026-07-13',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200"
  },
  {
    slug: 'deepseek-7-4-billion-funding-deal-china-ai-map-2026',
    title: "DeepSeek's $7.4 Billion Question: The Deal That Changed China's AI Map",
    category: "AI Industry",
    excerpt: "When DeepSeek closed its $7.4 billion funding round at a $50 billion valuation, it became China's most valuable AI startup. But beneath the headline lies a deal structure that could define the future of state-capital collaboration in Chinese technology.",
    date: '2026-07-12',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=1200&q=80"
  },
  {
    slug: 'china-humanoid-robot-100000-units-production-milestone-2026',
    title: "The 100,000 Robot Year: How China's Humanoid Industry Crossed the Mass Production Threshold",
    category: "AI Hardware",
    excerpt: "China's humanoid robot production is set to exceed 100,000 units in 2026 — a staggering leap from 1,800 the year before. From factory floors in Shanghai to supply chains in Shenzhen, the world's largest robot manufacturing ecosystem is hitting its stride.",
    date: '2026-07-11',
    readTime: '17 min read',
    image: "https://images.unsplash.com/photo-1676299081847-824916de030a?w=1200&q=80"
  },
  {
    slug: 'china-ai-terminals-overtake-humanoid-robot-factory-2026',
    title: "China's AI Terminal Revolution: How Smart Devices and Humanoid Robots Overtook the Old World",
    category: "AI Hardware",
    excerpt: "2026 is the year AI devices overtook non-AI in China. With 100 million+ AI terminals shipped, 100,000 humanoid robots entering factories, and a trillion-RMB industry growing at 30%+, China's consumer tech landscape has crossed an irreversible threshold.",
    date: '2026-07-10',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1523961131990-5ea7c61b2107?w=1200&q=80"
  },
  {
    slug: 'china-ai-companion-ban-doubao-qwen-digital-friends-lost-2026',
    title: "China's AI Companion Ban: When 345 Million Users Lose Their Digital Friends — and What It Means for the Global AI Industry",
    category: "AI Policy",
    excerpt: "On July 15, 2026, China's first-ever regulation targeting AI emotional companionship takes effect. ByteDance's Doubao and Alibaba's Qwen are shutting down custom agent features used by hundreds of millions. Users are mourning digital friends on Weibo. This is the world's first national AI companion ban — and Silicon Valley is watching closely.",
    date: '2026-07-09',
    readTime: '18 min read',
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=1200&q=80"
  },
  {
    slug: 'bytedance-200-billion-ai-infrastructure-china-arms-race-2026',
    title: "ByteDance's $29 Billion AI Bet: How China's Quiet Infrastructure Arms Race Is Reshaping Global Computing",
    category: "AI Infrastructure",
    excerpt: "\"ByteDance's $29 Billion AI Bet: How China's Quiet Infrastructure Arms Race Is Reshaping Global Computing Photo by NASA on Unsplash",
    date: '2026-07-08',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&q=80"
  },
  {
    slug: 'china-ai-companion-law-countdown-doubao-qwen-shutdown-2026',
    title: "Seven Days to Digital Heartbreak: Inside China's AI Companion Law Countdown",
    category: "AI Policy",
    excerpt: "Seven Days to Digital Heartbreak: Inside China's AI Companion Law Countdown Beijing, July 8, 2026 — In exactly seven days, China's landmark AI...",
    date: '2026-07-08',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=1200&q=80"
  },
  {
    slug: 'alibaba-bans-claude-code-hidden-spyware-ai-war-2026',
    title: "The Code That Wasn't Supposed to Be Found: How Anthropic's Hidden Spyware Turned Alibaba Against Claude Code",
    category: "AI Industry",
    excerpt: "When a Reddit user reverse-engineered Claude Code and found XOR-encrypted tracking routines that singled out Chinese developers, the story of who was spying on whom in the US-China AI war flipped overnight. Inside the hidden code, the industrial-scale 'distillation attack' allegations, and Alibaba's July 2026 decision to ban Anthropic products company-wide.",
    date: '2026-07-07',
    readTime: '23 min read',
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=1200&q=80"
  },
  {
    slug: 'china-ai-export-revolution-global-intelligence-2026',
    title: "The Great AI Export: How China's Intelligence Industry Is Rewiring the Global Tech Map",
    category: "AI Industry",
    excerpt: "In 2026, China became the world's largest exporter of AI intelligence—not just hardware, but the algorithms, models, and solutions that power global innovation. With $16.5 billion in quarterly startup funding, 170+ countries hosting Chinese AI businesses, and a 1000-fold explosion in daily token consumption, something fundamental has shifted.",
    date: '2026-07-06',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200&q=80"
  },
  {
    slug: 'china-ai-companion-ban-virtual-lovers-regulation-2026',
    title: "China's AI Heartbreak: How a New Law Is Erasing Millions of Virtual Companions",
    category: "AI Policy",
    excerpt: "On July 4, ByteDance's Doubao and Alibaba's Qwen shocked 500 million users with identical announcements: their AI companion features would vanish on July 15, the very day China's groundbreaking AI anthropomorphic interaction regulation takes effect.",
    date: '2026-07-05',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=1200&q=80"
  },
  {
    slug: 'china-ai-video-revolution-seedance-sora-2026',
    title: "From Sora to Seedance: How China Conquered the AI Video Revolution",
    category: "AI Industry",
    excerpt: "Eighteen months after OpenAI's Sora dazzled the world, the AI video landscape has been redrawn. ByteDance's Seedance 2.5 is launching in July 2026 with native 4K, 30-second outputs, and a $2 billion enterprise ARR. An AI-generated feature film just premiered at Cannes. And China's AI video ecosystem has grown from a curiosity into a global production infrastructure. This is the story of how the world learned to make movies with algorithms—and how China built the factory.",
    date: '2026-07-04',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=1200&q=80"
  },
  {
    slug: 'lingsheng-supercomputer-china-cpu-ai-paradigm-2026',
    title: "LingSheng's Bet Against GPUs: How China's CPU-Only Supercomputer Could Rewrite the Rules of AI",
    category: "AI Hardware",
    excerpt: "China's LingSheng supercomputer just claimed the TOP500 crown with a radical proposition: what if the future of AI computing isn't about GPUs at all?",
    date: '2026-07-04',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&h=600&fit=crop"
  },
  {
    slug: 'waic-2026-global-ai-diplomacy-shanghai',
    title: "WAIC 2026: The Conference That Rewrote Global AI Diplomacy",
    category: "AI Industry",
    excerpt: "In eight years, Shanghai's World Artificial Intelligence Conference grew from a local trade show into the world's most consequential AI diplomacy platform. With 1,400+ international guests, 300+ global product debuts, and the inaugural WAIC Academic conference co-chaired by Turing laureate Andrew Yao and reinforcement learning pioneer Richard Sutton, WAIC 2026 is not merely an exhibition. It is a declaration of where the global AI order is heading.",
    date: '2026-07-03',
    readTime: '15 min read',
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&q=80"
  },
  {
    slug: 'china-multimodal-ai-revolution-end-text-only-2026',
    title: "The End of Text-Only AI: How China's Multimodal Revolution Is Redefining What Machines Can See",
    category: "AI Technology",
    excerpt: "In July 2026, China's AI industry quietly crossed a threshold that most Western observers missed. For the first time, multimodal models—systems that see, hear, and reason across images, video, and text—began outperforming their text-only predecessors on the metrics that matter: enterprise adoption, developer preference, and revenue. This is the story of how the world's largest AI market ended the text-only era.",
    date: '2026-07-02',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200&q=80"
  },
  {
    slug: 'china-ai-video-captured-global-creative-frontier-2026',
    title: "How China's AI Video Models Captured the Global Creative Frontier",
    category: "Analysis",
    excerpt: "Beijing, July 1, 2026 — In the summer of 2024, a short-video company from Beijing released an AI video generator that most Western observers dismissed as...",
    date: '2026-07-01',
    readTime: '20 min read',
    image: "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=1200&q=80"
  },
  {
    slug: 'china-global-autonomous-driving-regulation-ads-gtr-2026',
    title: "China Writes the Rules for Global Autonomous Driving: How the ADS GTR Signals a New Era of Technical Leadership",
    category: "AI",
    excerpt: "China Writes the Rules for Global Autonomous Driving: How the ADS GTR Signals a New Era of Technical Leadership On a Tuesday afternoon in late June,...",
    date: '2026-06-30',
    readTime: '23 min read',
    image: "https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?w=1200&h=600&fit=crop"
  },
  {
    slug: 'ai-on-era-mwc-shanghai-2026-china-networks-intelligent',
    title: "The AI-ON Era: How MWC Shanghai 2026 Marked the Moment China's Networks Became Intelligent",
    category: "AI Applications",
    excerpt: "The Summit That Changed Everything On the afternoon of June 24, 2026, in the Kerry Hotel Pudong, a few hundred telecom executives, government officials,...",
    date: '2026-06-29',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&q=80"
  },
  {
    slug: 'china-ai-benchmark-war-caught-frontier-2026',
    title: "The Great AI Benchmark War: How Chinese Models Caught the Frontier in 2026",
    category: "AI Industry",
    excerpt: "The Myth That Won't Die At dinner tables in San Francisco, investment briefings in London, and tech podcasts streamed from New York, one assumption...",
    date: '2026-06-28',
    readTime: '23 min read',
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200"
  },
  {
    slug: 'bytedance-30-billion-ai-capex-huawei-chips-2026',
    title: "ByteDance's $30 Billion AI Gambit: How One Budget Revision Is Rewriting China's Chip Playbook",
    category: "AI Infrastructure",
    excerpt: "ByteDance's Beijing headquarters. The company's expanded AI infrastructure spending reflects a broader shift toward domestic semiconductor supply chains....",
    date: '2026-06-27',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&h=400&fit=crop"
  },
  {
    slug: 'pentagon-blacklist-alibaba-baidu-byd-china-tech-decoupling-2026',
    title: "The Pentagon's Blacklist Gamble: Why Adding Alibaba, Baidu, and BYD to the Military List Is Accelerating the Very Decoupling It Seeks to Prevent",
    category: "AI Policy",
    excerpt: "On June 8, 2026, the Pentagon added Alibaba, Baidu, BYD, and NIO to its Chinese Military Companies list. By June 24, Alibaba had sued the U.S. government. The blacklist now covers 188 entities—a 45% expansion in one year. But the real story isn't the legal fight. It's how Washington's escalating pressure is forcing China's tech giants to build a parallel ecosystem that may soon need no American technology at all.",
    date: '2026-06-26',
    readTime: '15 min read',
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&q=80"
  },
  {
    slug: 'china-embodied-ai-revolution-robotics-awakening-2026',
    title: "China's Embodied AI Revolution: From Laboratory Curiosity to Trillion-Yuan Industrial Machine",
    category: "AI Hardware",
    excerpt: "In 2025, embodied AI barely existed in China's government vocabulary. By June 2026, the country hosts 140+ humanoid robot manufacturers, ships thousands of units globally, and is racing toward a ¥1 trillion market. How did China's physical AI industry go from zero to warp speed in eighteen months?",
    date: '2026-06-25',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1523961131990-5ea7c61b2107?w=1200&q=80"
  },
  {
    slug: 'china-ai-consumption-gambit-17-point-plan-2026',
    title: "China's AI+Consumption Gambit: Beijing's 17-Point Plan to Turn 1.4 Billion Shoppers Into the World's Smartest Consumers",
    category: "AI Policy",
    excerpt: "On June 18, 2026, eight Chinese ministries released a sweeping 17-point policy to fuse AI with consumer life—from AI phones and smart homes to humanoid robots and brain-computer interfaces. Experts call it China's 'new energy vehicle moment' for artificial intelligence. Here's what the world's largest AI consumption experiment actually looks like.",
    date: '2026-06-24',
    readTime: '15 min read',
    image: "https://images.unsplash.com/photo-1556740758-90de374c12ad?w=1200&q=80"
  },
  {
    slug: 'china-ai-agent-revolution-2026',
    title: "China's AI Agent Revolution: Why 2026 Is the Year Agents Stop Chatting and Start Working",
    category: "AI Industry",
    excerpt: "While Western tech media obsesses over GPT-5 benchmarks, China's tech giants have quietly built the world's first large-scale AI agent economy. With 79% enterprise adoption, billion-user platforms embedding agents directly into WeChat, and inference costs 3-5x below Western levels, 2026 is the year AI agents stop chatting and start working.",
    date: '2026-06-23',
    readTime: '14 min read',
    image: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1200&q=80"
  },
  {
    slug: 'huawei-ascend-12-billion-ai-chip-surge-global-bifurcation-2026',
    title: "The Silicon Curtain: How Huawei's $12 Billion AI Chip Surge Is Splitting Global AI in Two",
    category: "AI Technology",
    excerpt: "Huawei's AI chip revenue is projected to hit $12 billion in 2026 — a 60% surge driven by Alibaba, ByteDance, Tencent, and Baidu shifting from NVIDIA to domestic silicon. As DeepSeek trains on Ascend, ByteDance plans 350,000 custom chips, and Chinese models close within 5 points of the American frontier, the global AI infrastructure map is splitting in two.",
    date: '2026-06-22',
    readTime: '21 min read',
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&q=80"
  },
  {
    slug: 'qwen-billion-downloads-china-open-source-ai-dominance-2026',
    title: "Qwen's Open-Source Conquest: How China's AI Model Captured a Billion Downloads and Redrew Global Developer Economics",
    category: "AI Ecosystem",
    excerpt: "Alibaba's Qwen model family has become the most downloaded open-source AI system in history, fundamentally shifting the global developer ecosystem...",
    date: '2026-06-21',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1639322537228-f710d846310a?w=1200&h=600&fit=crop"
  },
  {
    slug: 'baidu-apollo-go-swiss-level4-robotaxi-permit-europe-2026',
    title: "The Swiss Connection: How Baidu's Apollo Go Beat Waymo and Tesla to Europe's First Level 4 Robotaxi Permit",
    category: "AI Robotics",
    excerpt: "On June 16, 2026, Baidu's Apollo Go received a Level 4 autonomous driving permit in Switzerland — the first on European soil. With 22 million cumulative rides, 330 million kilometers logged, and a partnership with Swiss Post's PostBus, Baidu just leaped ahead of Waymo and Tesla in the global robotaxi race.",
    date: '2026-06-20',
    readTime: '14 min read',
    image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=1200&q=80"
  },
  {
    slug: 'china-profit-future-gamble-ai-war-2026',
    title: "The Profit-for-Future Gamble: How China's Tech Giants Sacrificed $100 Billion in Profits to Win the AI War",
    category: "AI Industry",
    excerpt: "ByteDance profits collapsed 70%. Alibaba committed ¥3.8 trillion. Tencent's capex surged 91%. Yet valuations soared, investors cheered, and employees got richer. Welcome to China's 'profit-for-future' AI economy — where losing money is the new winning strategy.",
    date: '2026-06-19',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&q=80"
  },
  {
    slug: 'china-ai-iron-cage-governance-regime-2026',
    title: "China's AI Iron Cage: How Beijing Built the World's Most Prescriptive Algorithmic Regulatory Regime in 1,826 Days",
    category: "AI Policy",
    excerpt: "While Western policymakers debate AI safety frameworks, China has already erected a three-pillar regulatory architecture that mandates registration for every algorithm, labels every AI-generated pixel, and can fine companies up to ¥5 million—or imprison executives for seven years. This is not a draft proposal. It is live law, enforced daily.",
    date: '2026-06-18',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=1200&q=80"
  },
  {
    slug: 'china-low-altitude-economy-drones-ai-500bn-airspace-2026',
    title: "China's Low-Altitude Economy: How Drones, AI, and eVTOLs Are Building a $500 Billion Airspace Industry",
    category: "AI Business",
    excerpt: "With 1.2 million cargo drone flights in 2025, 70% of global consumer drone production, and a $500 billion market projection by 2035, China's low-altitude economy has moved from policy concept to commercial reality. Here's how Shenzhen, Meituan, DJI, and a fleet of eVTOL startups are reshaping the skies.",
    date: '2026-06-17',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=1200&q=80"
  },
  {
    slug: 'china-embodied-intelligence-revolution-2026',
    title: "China's Embodied Intelligence Revolution: From Spring Festival Gala to Factory Floor",
    category: "AI Robotics",
    excerpt: "Eight out of ten humanoid robots worldwide now come from China. From the CCTV Spring Festival Gala to factory floors, China's embodied intelligence industry has shifted from laboratory curiosity to mass production reality. Here's how Unitree, AgiBot, and 140+ manufacturers are building the physical AI future.",
    date: '2026-06-16',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1523961131990-5ea7c61b2107?w=1200&q=80"
  },
  {
    slug: 'china-physical-ai-awakening-world-models-robot-ipos-295b-bet-2026',
    title: "China's Physical AI Awakening: World Models, Robot IPOs, and the $295 Billion Bet on Embodied Intelligence",
    category: "AI",
    excerpt: "In a single week, China unveiled the world's first general world foundation model, a humanoid robot maker filed for IPO, and Beijing prepared a $295 billion nationwide AI buildout. The physical AI era has arrived.",
    date: '2026-06-15',
    readTime: '18 min read',
    image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=1200"
  },
  {
    slug: 'china-industrial-ai-revolution-smart-factories-2026',
    title: "China's 30,000 Smart Factories: Why the Real AI War Is Happening on the Factory Floor, Not in Chatbots",
    category: "AI Hardware",
    excerpt: "While Silicon Valley obsesses over chatbot leaderboards, China has quietly deployed 30,000 smart factories, produced 143,608 industrial robots in two months, and built an industrial AI ecosystem that triples factory output without adding workers. The numbers tell a story the West isn't hearing.",
    date: '2026-06-14',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=1200&q=80"
  },
  {
    slug: 'ai-builds-ai-forgetrain-modelbest-china-2026',
    title: "AI Builds AI: How a Chinese Lab Taught Artificial Intelligence to Write Its Own Training Framework — and Beat NVIDIA",
    category: "AI Technology",
    excerpt: "ModelBest's ForgeTrain is the world's first production-grade LLM pre-training framework written entirely by AI. It trains models 10% faster than NVIDIA's Megatron-LM on identical H100 hardware, runs on both NVIDIA and Huawei Ascend chips, and trained MiniCPM5-1B — the world's top-ranked sub-2B parameter model.",
    date: '2026-06-13',
    readTime: '18 min read',
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200"
  },
  {
    slug: 'china-ai-network-doctrine-miit-three-year-plan-2026',
    title: "China's AI Network Doctrine: How the 2026-2028 Plan Is Wiring Intelligence Into Every Fiber",
    category: "AI Policy",
    excerpt: "China's MIIT just released a three-year implementation plan to integrate AI with information and communications networks. With 75% compute latency targets, 30+ high-value use cases, and autonomous network goals by 2028, this is not just policy—it is infrastructure-as-strategy.",
    date: '2026-06-13',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200"
  },
  {
    slug: 'forbes-china-ai-top-50-six-decoupling-signals-2026',
    title: "The Forbes China AI TOP 50: Six Decoupling Signals That Silicon Valley Can't Ignore",
    category: "AI",
    excerpt: "Forbes China's 2026 AI TOP 50 rankings reveal six decoupling signals across foundation models, silicon, embodied intelligence, and frontier science that prove China's AI ecosystem has fundamentally separated from Western technology at every layer.",
    date: '2026-06-13',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=1200"
  },
  {
    slug: 'glm-5-1-open-source-crown-beijing-2026',
    title: "GLM-5.1: The 754B-Parameter Open-Source MoE That Beat GPT-5.4 on Real-World Coding — and Trained Without NVIDIA",
    category: "AI",
    excerpt: "On April 7, 2026, a Chinese AI research lab quietly uploaded a set of model weights to Hugging Face. There was no splashy livestream. No carefully...",
    date: '2026-06-13',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=1200"
  },
  {
    slug: 'unitree-robotics-ipo-china-humanoid-robot-first-stock-2026',
    title: "Unitree's IPO Sprint: How a Chinese Robot Maker Went From Zero to ¥17 Billion in Eight Years",
    category: "AI Robotics",
    excerpt: "Unitree's IPO Sprint: How a Chinese Robot Maker Went From Zero to ¥17 Billion in Eight Years On the morning of June 1, 2026, Wang Xingxing sat in a...",
    date: '2026-06-13',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1676299081847-824916de030a?w=1200"
  },
  {
    slug: 'gaokao-agent-wars-china-ai-battleground-2026',
    title: "The Gaokao Agent Wars: How China's 12.9 Million Student Exam Became Tech's Biggest AI Battleground",
    category: "AI Business",
    excerpt: "The Gaokao Agent Wars: How China's 12.9 Million Student Exam Became Tech's Biggest AI Battleground It was 11:47 PM on June 10, 2026, and 17-year-old Liu...",
    date: '2026-06-12',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1200"
  },
  {
    slug: 'triple-silicon-china-ai-chip-independence-2026',
    title: "The Triple Silicon Gambit: How China's AI Chip Surge Is Forging an Independent Path to AGI",
    category: "AI Hardware",
    excerpt: "The Triple Silicon Gambit: How China's AI Chip Surge Is Forging an Independent Path to AGI The conventional wisdom says US semiconductor export controls...",
    date: '2026-06-11',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200"
  },
  {
    slug: 'china-embodied-ai-revolution-funding-world-models-2026',
    title: "China's Embodied AI Revolution: The $3.3 Billion Quarterly Funding Frenzy, World Models, and the Physical AI Economy",
    category: "AI Robotics",
    excerpt: "China's embodied AI sector raised $3.3 billion in Q1 2026 alone, with Unitree Robotics targeting a $7 billion IPO and ByteDance declaring world models its top priority. Here's how physical AI is becoming China's next trillion-dollar industry.",
    date: '2026-06-10',
    readTime: '14 min read',
    image: "https://images.unsplash.com/photo-1567789884554-0b844b597180?w=1200"
  },
  {
    slug: 'china-ai-agent-army-126-platforms-67-enterprise-adoption-2026',
    title: "China's AI Agent Army: 126 Platforms, 67% Enterprise Adoption, and Why the Copycat Narrative Is Wrong",
    category: "AI",
    excerpt: "Image: The abstract architecture of AI Agent networks — Photo by Unsplash The Western narrative about China's AI Agent ecosystem is almost comically wrong.",
    date: '2026-06-09',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1523961131990-5ea7c61b2107?w=1200"
  },
  {
    slug: 'ai-thesis-writing-phenomenon-china-2026',
    title: "The AI Thesis Writing Phenomenon: How Chinese Students Are Redefining Academic Work with Generative AI",
    category: "AI Video",
    excerpt: "China's 12 million graduates are facing an existential question: write their thesis themselves, or let AI do it? The answer is reshaping academia. China's...",
    date: '2026-06-08',
    readTime: '16 min',
    image: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=1200&q=80"
  },
  {
    slug: 'tencent-wechat-ai-agent-billion-users-china-2026',
    title: "Tencent's WeChat AI Agent: The 1.4 Billion-User Bet That Reshaped China's Tech Markets Overnight",
    category: "AI Industry",
    excerpt: "A Financial Times report on June 2 revealed Tencent is testing an AI agent inside WeChat. The result: a $41 billion market cap surge, China's biggest agentic AI platform, and a direct challenge to Alibaba and ByteDance.",
    date: '2026-06-07',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=1200"
  },
  {
    slug: 'china-ai-ipo-wave-zhipu-minimax-2026',
    title: "China's AI IPO Wave: How Zhipu and MiniMax Are Rewriting the Rules of AI Capitalization",
    category: "AI Business",
    excerpt: "China's AI unicorns are trading at valuations that would have seemed impossible just 18 months ago Something historic is happening in China's AI industry.",
    date: '2026-06-04',
    readTime: '16 min',
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=1200&h=600&fit=crop"
  },
  {
    slug: 'ai-interview-coaching-china-graduates-job-market-2026',
    title: "AI Interview Coaching: How Chinese Graduates Are Using AI to Crack the Job Market (+120% Trend Explosion)",
    category: "AI Applications",
    excerpt: "With Xiaohongshu views surging 120% in one week, AI interview coaching has become the hottest trend among Chinese graduates facing a brutal job market. We analyze 6 platforms, university adoption programs, and the DeepSeek-V3 technology powering this revolution.",
    date: '2026-06-03',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=1200&q=80"
  },
  {
    slug: 'china-ai-agent-era-140-trillion-tokens-2026',
    title: "China's AI Agent Era: How 140 Trillion Daily Tokens, New Regulations, and a DeepSeek Price War Are Reshaping Global AI",
    category: "AI Industry",
    excerpt: "China's AI Agent Era: How 140 Trillion Daily Tokens, New Regulations, and a DeepSeek Price War Are Reshaping Global AI June 2026 marks a watershed moment...",
    date: '2026-06-03',
    readTime: '17 min read',
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1200&h=600&fit=crop"
  },
  {
    slug: 'minimax-300m-users-arr-doubles-a-share-ipo-china-ai-export-2026',
    title: "MiniMax Hits 300M Users and Doubles ARR in 60 Days: The Anatomy of China's Most Successful AI Export",
    category: "AI Business",
    excerpt: "In 60 days, MiniMax doubled its annual recurring revenue to approximately $300M, crossed 300 million global users, and launched its A-share IPO process. With 73% of revenue from international markets, the company has built the most successful Chinese AI export since TikTok—and the financials reveal both extraordinary growth and a brutal path to profitability.",
    date: '2026-06-02',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=1200&q=80"
  },
  {
    slug: 'china-ai-drama-revolution-bytedance-650m-empire-2026',
    title: "China's AI Drama Revolution: How ByteDance Built a $650M Short-Content Empire in 90 Days",
    category: "AI Video",
    excerpt: "In 90 days, China's AI short drama market expanded sixfold from $100M to $650M. ByteDance's integrated ecosystem—Doubao for scripts, Jimeng for visuals, Volcano Engine for compute, and Red Fruit for distribution—has compressed production cycles from 90 days to 7-10 days at 20% of traditional cost. With 150M overseas active users and nearly 50% willing to pay, this is China's most explosive AI content revolution yet.",
    date: '2026-06-01',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1200&q=80"
  },
  {
    slug: 'china-humanoid-robot-tsunami-2026-50k-units-global-dominance',
    title: "China's Humanoid Robot Tsunami: 50,000 Units, 700% Growth, and Why 2026 Is the Year Everything Changed",
    category: "Embodied AI",
    excerpt: "China's humanoid robot industry is scaling from thousands to tens of thousands of units in a single year—a shift that is redefining global robotics...",
    date: '2026-05-31',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1676299081847-824916de030a?w=1200&h=600&fit=crop"
  },
  {
    slug: 'alibaba-zhenwu-m890-ai-chip-china-silicon-sovereignty',
    title: "Alibaba's Zhenwu M890: The 3x AI Chip That Just Shipped 560,000 Units and Rewrote China's Silicon Playbook",
    category: "AI Infrastructure",
    excerpt: "Alibaba's T-Head unveiled the Zhenwu M890 AI chip with 3x performance, 144GB HBM, and 800GB/s interconnect. With 560,000 units already shipped to 400+ customers, this is how China is building an AI chip empire without NVIDIA.",
    date: '2026-05-30',
    readTime: '17 min read',
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200"
  },
  {
    slug: 'china-ai-inflection-point-may-2026',
    title: "China's AI Inflection Point: From Burn Rate to Revenue Rate (2026)",
    category: "AI Business",
    excerpt: "May 2026 delivered the clearest signal yet that China's AI industry has shifted from a cash-burning sprint to a revenue-generating marathon. DeepSeek accepted its first external funding, Alibaba reported AI revenue exceeding 50% of total cloud income, and ByteDance committed $23 billion to infrastructure. Here's the full breakdown.",
    date: '2026-05-29',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200&q=80"
  },
  {
    slug: 'china-ai-models-dominate-global-api-traffic-token-export-2026',
    title: "China's AI Models Dominate Global API Traffic: The Token Export Boom Silicon Valley Didn't See Coming",
    category: "AI Business",
    excerpt: "Chinese AI models now consume 61% of top-tier global API token volume. MiniMax M2.5 alone processes 5 trillion tokens weekly on OpenRouter — more than GPT-5.5 and Claude 4 combined. Here's how China's 'token export' economy became the invisible infrastructure powering developers worldwide.",
    date: '2026-05-28',
    readTime: '17 min read',
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=1200&auto=format&fit=crop"
  },
  {
    slug: 'china-ai-fraud-epidemic-deepfake-panic-2026',
    title: "China's AI Fraud Epidemic: Inside the 5.6 Billion View Deepfake Panic Reshaping Digital Trust",
    category: "AI Security",
    excerpt: "A 62-year-old retired teacher in Hangzhou lost ¥280,000 to an AI deepfake video call from her 'son.' The story sparked a national conversation reaching 5.6 billion views across Chinese social media — the fastest-growing AI topic at +300% week-over-week. What began as scattered fraud reports has crystallized into a full-blown public anxiety crisis, forcing regulators and AI companies into an unprecedented response.",
    date: '2026-05-27',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=1200&h=600&fit=crop"
  },
  {
    slug: 'ai-digital-humans-china-billion-dollar-livestream-revolution',
    title: "China's AI Digital Human Explosion: The 100 Billion Yuan Avatar Economy Reshaping E-Commerce",
    category: "AI Video",
    excerpt: "In February 2026, Chinese regulators drew a hard line: every AI-generated face in a livestream must be labeled. Two months later, that rule hasn't slowed...",
    date: '2026-05-26',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&h=400&fit=crop"
  },
  {
    slug: 'deepseek-permanent-75-percent-api-price-cut-ai-war-2026',
    title: "DeepSeek's Permanent 75% Price Cut: The API War That Just Changed Everything",
    category: "AI Infrastructure",
    excerpt: "On May 22, DeepSeek made its 2.5 discount permanent. At $0.025 per million cached tokens, the company's API pricing isn't just cheap — it's a declaration that inference cost is heading toward zero, and every competitor must now adapt or die.",
    date: '2026-05-25',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=1200"
  },
  {
    slug: 'china-storage-twin-giants-ipo-ai-compute-2026',
    title: "China's Storage Twin Giants Race to IPO: A $500B Revaluation of the AI Compute Foundation",
    category: "AI Infrastructure",
    excerpt: "Changxin Technology and Yangtze Memory Technologies, China's two storage chip giants, are both charging toward IPO. With combined Q1 revenue exceeding $10B and a $500B+ market opportunity ahead, this is the moment China's semiconductor industry goes from 'domestic replacement' to 'global pricing power.'",
    date: '2026-05-24',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200"
  },
  {
    slug: 'china-embodied-intelligence-infrastructure-ndrc-robots-factories-malls-homes',
    title: "China's Embodied Intelligence Infrastructure Push: NDRC Unveils National Plan to Put Robots in Factories, Malls, and Homes",
    category: "AI Policy & Infrastructure",
    excerpt: "China's NDRC just announced a national infrastructure plan for embodied intelligence, with dedicated training bases, 'big brain/small brain' model architecture, and a roadmap to deploy robots across factories, shopping malls, and homes by 2027.",
    date: '2026-05-23',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1676299081847-824916de030a?w=1200"
  },
  {
    slug: 'huawei-pangu-ultra-moe-718b-chinese-silicon',
    title: "Huawei Pangu Ultra MoE: The 718-Billion-Parameter Model Built Entirely on Chinese Silicon",
    category: "AI Infrastructure",
    excerpt: "Huawei's Pangu Ultra MoE packs 718 billion parameters and was trained end-to-end on Ascend AI chips. Here's why this milestone proves China no longer needs NVIDIA to build world-class large language models.",
    date: '2026-05-22',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=1200"
  },
  {
    slug: 'china-ai-global-expansion-minimax-2-billion-users-2026',
    title: "China AI Goes Global: How MiniMax Built a 236 Million User Empire from Shanghai",
    category: "AI Trends",
    excerpt: "China AI Goes Global: How MiniMax Built a 236 Million User Empire from Shanghai In 2025, a Shanghai startup earned 73% of its revenue from overseas...",
    date: '2026-05-21',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1626908013351-800ddd734b8a?w=1200&h=600&fit=crop"
  },
  {
    slug: 'china-ai-interview-revolution-2026',
    title: "AI Interview Coaching: China's 2026 Grad Job Market Hack",
    category: "AI Trends",
    excerpt: "AI Interview Coaching: China's 2026 Grad Job Market Hack Xiaohongshu searches for \"AI interview coaching\" surged 120% in one week. Six hundred eighty...",
    date: '2026-05-20',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1523961131990-5ea7c61b2107?w=1200&h=600&fit=crop"
  },
  {
    slug: 'china-ai-chip-renaissance-q1-2026',
    title: "China's AI Chip Renaissance: The Quarter That Changed Everything",
    category: "AI Infrastructure",
    excerpt: "China's AI Chip Renaissance: The Quarter That Changed Everything Cambricon's profit surge of 185%. Hygon crossing ¥40 billion in quarterly revenue. Moore...",
    date: '2026-05-19',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1592659762303-90081d34b277?w=1200&h=600&fit=crop"
  },
  {
    slug: 'china-ai-ppt-revolution-3-minute-decks-2026',
    title: "The 3-Minute Deck Revolution: How China's Office Workers Are Using AI to Replace PowerPoint Design",
    category: "AI Applications",
    excerpt: "The 3-Minute Deck Revolution: How China's Office Workers Are Using AI to Replace PowerPoint Design China's office workers are abandoning manual slide...",
    date: '2026-05-18',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1644088379091-d574269d422f?w=1200&h=600&fit=crop"
  },
  {
    slug: 'china-ai-hallucination-blind-spot-crisis-2026',
    title: "The Hallucination Blind Spot: How China's 249M AI Users Became Perfect Prey for a Deception Epidemic",
    category: "AI Safety",
    excerpt: "The Hallucination Blind Spot: How China's 249M AI Users Became Perfect Prey for a Deception Epidemic On May 17, 2025, two reports dropped within hours of...",
    date: '2026-05-17',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?w=1200&h=600&fit=crop"
  },
  {
    slug: 'china-ai-creator-economy-digital-humans-2026',
    title: "China's AI Creator Economy: How Digital Humans and $45B Valuations Are Reshaping Global Content",
    category: "AI Applications",
    excerpt: "China's AI Creator Economy: How Digital Humans and $45B Valuations Are Reshaping Global Content On May 6, 2026, while Western markets were digesting...",
    date: '2026-05-16',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=800&h=400&fit=crop"
  },
  {
    slug: 'china-ai-invisible-empire-consumer-apps-2026',
    title: "The Invisible Empire: How China's AI Consumer Apps Quietly Conquered 2.5 Billion Users — And Why the World Barely Noticed",
    category: "AI Business",
    excerpt: "The Invisible Empire: How China's AI Consumer Apps Quietly Conquered 2.5 Billion Users — And Why the World Barely Noticed While Silicon Valley obsessed...",
    date: '2026-05-13',
    readTime: '22 min read',
    image: "https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=1200&h=600&fit=crop"
  },
  {
    slug: 'china-six-networks-trillion-infrastructure-ai-compute-2026',
    title: "China's $7 Trillion 'Six Networks' Strategy: When AI Compute Gets the Same Priority as Water and Electricity",
    category: "AI Policy",
    excerpt: "On April 28, 2026, China's Politburo did something unprecedented: it elevated compute networks (算力网) to the same strategic tier as water networks, power...",
    date: '2026-05-13',
    readTime: '17 min read',
    image: "https://images.unsplash.com/photo-1594915440248-1e419eba6611?w=1200"
  },
  {
    slug: 'china-ai-olympus-65-billion-war-future-intelligence-2026',
    title: "China's AI Olympus: The $65 Billion War for the Future of Intelligence",
    category: "AI Business",
    excerpt: "In seven days, Chinese AI companies raised more capital than the entire European AI sector raised in 2025. They did it while simultaneously releasing models that collectively hold the top five positions on global open-source leaderboards. This is not a funding cycle. This is an arms race with a product launch attached.",
    date: '2026-05-11',
    readTime: '22 min read',
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200"
  },
  {
    slug: 'china-agent-era-national-policy-ai-terminal-standards-anthropic-trillion-2026',
    title: "China's Agent Era Begins: National Policy Framework, AI Terminal Standards, and the Trillion-Dollar Global AI Race",
    category: "AI Applications",
    excerpt: "Three Chinese ministries jointly issued the most comprehensive national policy framework for AI agent governance to date. AI terminal intelligence grading standards were released. Anthropic nears a $1 trillion valuation. And China's AI models processed 8 trillion tokens in a single week. May 2026 will be remembered as the month AI agents went mainstream.",
    date: '2026-05-09',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&q=80"
  },
  {
    slug: 'doubao-charging-ai-free-era-ends-china-2026',
    title: "Doubao Starts Charging: How China's Biggest AI App Ended the Free Era — and What It Means for 345 Million Users",
    category: "AI Business",
    excerpt: "ByteDance's Doubao, China's largest AI app with 345M MAU, just launched paid tiers from $9.50 to $72/month. Here's why 120 trillion daily tokens made free unsustainable, and what this signals for the global AI industry.",
    date: '2026-05-07',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?q=80&w=1200&auto=format&fit=crop"
  },
  {
    slug: 'kimi-20-billion-valuation-china-ai-token-economy',
    title: "Kimi's $20 Billion Bet: How China's AI Token Economy Is Rewriting Global Power Dynamics",
    category: "AI Industry",
    excerpt: "Kimi hits a $20 billion funding round at $200 billion valuation while China's AI token consumption surges past the US for the third time. Here's what it means for the global AI landscape.",
    date: '2026-05-07',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&q=80"
  },
  {
    slug: 'deepseek-v4-promo-ending-analysis',
    title: "DeepSeek V4's 75% Promo Ends May 31: What Happens Next and Why the AI Pricing War Is Just Beginning",
    category: "AI Infrastructure",
    excerpt: "DeepSeek V4 launched on April 24, 2026, with a 75% promotional discount on its flagship Pro model. Originally set to expire on May 5, the offer has been...",
    date: '2026-05-05',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=800&h=400&fit=crop"
  },
  {
    slug: 'china-ai-deepfake-fraud-crisis-2026',
    title: "China's AI Deepfake Fraud Crisis: How 700,000 Annual Scams and a $40 Billion Global Threat Are Reshaping Trust in the Digital Age",
    category: "AI Safety",
    excerpt: "China's AI Deepfake Fraud Crisis: How 700,000 Annual Scams and a $40 Billion Global Threat Are Reshaping Trust in the Digital Age China's AI digital human...",
    date: '2026-05-03',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=800&h=400&fit=crop"
  },
  {
    slug: 'kimi-k2-6-open-source-coding-revolution',
    title: "Kimi K2.6: How a $18B Chinese Startup Is Rewriting the Rules of Open-Source AI Coding",
    category: "AI Infrastructure",
    excerpt: "Kimi K2.6: How a $18B Chinese Startup Is Rewriting the Rules of Open-Source AI Coding On April 20, 2026, while Silicon Valley was still processing...",
    date: '2026-05-02',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&h=400&fit=crop"
  },
  {
    slug: 'china-ai-global-surge-api-traffic-empire-2026',
    title: "From Made in China to Trained in China: The Untold Story of How Chinese AI Conquered Global Developers",
    category: "AI Industry",
    excerpt: "China's AI export model defies every precedent in technology history. Image: Unsplash China's technology exports have always followed a familiar playbook:...",
    date: '2026-05-01',
    readTime: '17 min read',
    image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=1200&q=80"
  },
  {
    slug: 'china-ai-agent-revolution-2026-policy-market',
    title: "Inside China's AI Policy Machine: How the Politburo's 'AI+ Action' Directive Is Rewriting Procurement Law",
    category: "AI Policy",
    excerpt: "\"The question isn't whether AI agents will replace human workers. The question is whether companies that don't deploy agents will be replaced by companies...",
    date: '2026-04-30',
    readTime: '17 min read',
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1200&h=600&fit=crop"
  },
  {
    slug: 'ai-compute-crunch-china-token-crisis-2026',
    title: "The Great AI Compute Crunch: How China's AI Boom Is Running Out of Tokens",
    category: "AI Infrastructure",
    excerpt: "China's AI revolution is facing an unexpected bottleneck. In April 2026, as DeepSeek launched its highly anticipated V4 model and Kimi pushed out K2.6,...",
    date: '2026-04-29',
    readTime: '17 min read',
    image: "https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=800&h=400&fit=crop"
  },
  {
    slug: 'bytedance-seed-brain-drain-70-engineers',
    title: "ByteDance's AI Brain Drain: 70 Top Engineers Exit Seed Team in 12 Months",
    category: "AI Trends",
    excerpt: "\"Bytedance's AI Brain Drain: 70 Top Engineers Exit Seed Team in 12 Months",
    date: '2026-04-28',
    readTime: '15 min read',
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&h=400&fit=crop"
  },
  {
    slug: 'deepseek-v4-million-token-china-ai-sovereignty',
    title: "DeepSeek V4: The Million-Token API Update That Signals China's AI Sovereignty Shift",
    category: "AI Infrastructure",
    excerpt: "DeepSeek's quiet API update on April 22 signals something far bigger than a context window expansion—it's the prelude to China's most significant AI model...",
    date: '2026-04-22',
    readTime: '17 min read',
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200&h=600&fit=crop"
  },
  {
    slug: 'china-embodied-intelligence-robot-marathon-2026',
    title: "China's Embodied Intelligence Revolution: When Robots Outrun Humans — April 2026",
    category: "AI Trends",
    excerpt: "China's Embodied Intelligence Revolution: When Robots Outrun Humans Meta Title: China's Embodied Intelligence Revolution: When Robots Outrun Humans —...",
    date: '2026-04-21',
    readTime: '18 min read',
    image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&h=400&fit=crop"
  },
  {
    slug: 'china-ai-avatar-revolution-2026',
    title: "China's AI Avatar Revolution: How 410 Million Views Signal a Global Content Creation Shift",
    category: "AI Industry",
    excerpt: "<!-- Hero Image -- AI avatar technology is reshaping content creation at unprecedented scale (Image: Unsplash)  China's AI Avatar Revolution: How 410...",
    date: '2026-04-18',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=1200&h=600&fit=crop"
  },
  {
    slug: 'stanford-ai-index-2026-china-rise',
    title: "Stanford AI Index 2026: China's 'Parallel Run' Era Has Arrived",
    category: "AI Trends",
    excerpt: "\"The Stanford campus at dusk, where the world's most authoritative AI report originates",
    date: '2026-04-17',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=1200&h=600&fit=crop"
  },
  {
    slug: 'alibaba-token-hub-100b-gambit',
    title: "Alibaba's $100B Token Gambit: Inside the Alibaba Token Hub Revolution Reshaping China's AI Economy",
    category: "AI Trends",
    excerpt: "On March 16, 2026, Alibaba did something unprecedented in corporate history: it named a core business unit after a technical metric. The Alibaba Token Hub...",
    date: '2026-04-16',
    readTime: '17 min',
    image: "https://images.unsplash.com/photo-1631914730601-6295d106b459?w=1200&h=600&fit=crop"
  },
  {
    slug: 'china-ai-agent-explosion-2025-enterprise-deployment',
    title: "China's AI Agent Explosion: How 126 Platforms and $1B+ in Enterprise Deals Are Reshaping Global Automation",
    category: "AI Trends",
    excerpt: "China's AI Agent ecosystem spans 126 development platforms and serves millions of enterprise users across manufacturing, e-commerce, and financial...",
    date: '2026-04-15',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=1200&h=600&fit=crop"
  },
  {
    slug: 'china-ai-model-war-april-2026-week-changed-everything',
    title: "The Week That Changed Everything: China's AI Model War Intensifies in April 2026",
    category: "AI Trends",
    excerpt: "The AI model wars: Chinese tech giants battle for dominance in the world's largest AI market. Photo by Google DeepMind / Unsplash The first week of April...",
    date: '2026-04-13',
    readTime: '17 min read',
    image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&q=80"
  },
  {
    slug: 'china-ai-chip-war-2026-us-sanctions',
    title: "The Great Silicon Wall: How China's AI Industry Is Defying U.S. Chip Sanctions in 2026",
    category: "AI Infrastructure",
    excerpt: "The Great Silicon Wall: How China's AI Industry Is Defying U.S. Chip Sanctions in 2026 ByteDance's $5.6 billion bet on Huawei. DeepSeek V4 launching on...",
    date: '2026-04-12',
    readTime: '17 min read',
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&h=600&fit=crop"
  },
  {
    slug: 'china-ai-model-wars-april-2026',
    title: "China's AI Model Wars: How Alibaba, ByteDance, and MiniMax Are Reshaping Global AI Competition in April 2026",
    category: "AI Trends",
    excerpt: "China's AI Model Wars: How Alibaba, ByteDance, and MiniMax Are Reshaping Global AI Competition in April 2026 The most intense week in Chinese AI...",
    date: '2026-04-11',
    readTime: '13 min read',
    image: "https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=1200&h=600&fit=crop"
  },
  {
    slug: 'modelbest-edge-ai-unicorn-2026',
    title: "ModelBest Becomes Unicorn: How Tsinghua's Edge AI Pioneer Is Reshaping On-Device Intelligence",
    category: "AI Trends",
    excerpt: "A quiet revolution in artificial intelligence is happening on the smallest screens. While tech giants battle for cloud dominance, ModelBest—a Tsinghua...",
    date: '2026-04-10',
    readTime: '13 min read',
    image: "https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=1200&h=600&fit=crop"
  },
  {
    slug: 'ai-interview-coaching-china-2025',
    title: "The AI Interview Coach Phenomenon: How Chinese Graduates Are Using AI to Crack the Job Market",
    category: "AI Trends",
    excerpt: "China's job market has become a battleground for millions of fresh graduates, and a surprising new weapon has emerged: AI interview coaches. In the past...",
    date: '2026-04-08',
    readTime: '16 min',
    image: "https://images.unsplash.com/photo-1521791136064-7986c2920216?w=1200&h=600&fit=crop"
  },
  {
    slug: 'china-ai-token-surge-gen-z',
    title: "China's AI Overtake: 31% Surge in Token Usage Signals Global Power Shift",
    category: "AI Trends",
    excerpt: "China's AI Overtake: 31% Surge in Token Usage Signals Global Power Shift China's AI revolution is accelerating beyond predictions. According to OpenRouter...",
    date: '2026-04-07',
    readTime: '13 min read',
    image: "https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=800&h=400&fit=crop"
  },
  {
    slug: 'china-ai-avatar-revolution-2025',
    title: "China's AI Avatar Revolution: 410M Views Transformed Content Creation Forever",
    category: "AI Trends",
    excerpt: "China's AI Avatar Revolution: How 410 Million Views Transformed Content Creation Forever The rise of faceless influencers and the $4.4 billion digital...",
    date: '2026-04-05',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1551434678-e076c223a692?w=1200&h=600&fit=crop"
  },
  {
    slug: 'china-ai-digital-human-revolution',
    title: "China's AI Digital Human Revolution: 80,000 Virtual Avatars Reshaping Content",
    category: "AI Applications",
    excerpt: "AI digital humans are becoming indistinguishable from real creators, sparking a revolution in China's content economy The creator economy in China has...",
    date: '2026-04-05',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&q=80"
  },
  {
    slug: 'doubao-12-trillion-token-explosion',
    title: "Doubao's 12 Trillion Token Explosion: How ByteDance Is Quietly Winning the Global AI Race",
    category: "AI Infrastructure",
    excerpt: "Doubao's 12 Trillion Token Explosion: How ByteDance Is Quietly Winning the Global AI Race The exponential rise of China's AI ecosystem is reshaping global...",
    date: '2026-04-04',
    readTime: '14 min read',
    image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=1200"
  },
  {
    slug: 'stepfun-terminal-ai-revolution',
    title: "StepFun's $7 Billion Bet: How China's AI Unicorn Is Winning the Terminal Race",
    category: "AI Infrastructure",
    excerpt: "StepFun's $7 Billion Bet: How China's AI Unicorn Is Winning the Terminal Race The Shanghai AI lab that abandoned the consumer chatbot race is now inside...",
    date: '2026-04-03',
    readTime: '10 min read',
    image: "https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=1200"
  },
  {
    slug: 'ai-thesis-writing-china',
    title: "AI Thesis Writing Explodes: How 12 Million Chinese Students Are Rewriting Academic Rules",
    category: "AI Chatbots",
    excerpt: "\"AI Thesis Writing Explodes: How 12 Million Chinese Students Are Rewriting Academic Rules",
    date: '2026-04-02',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=800&h=400&fit=crop"
  },
  {
    slug: 'doubao-bytedance',
    title: "ByteDance Doubao: The 200 Million User AI Assistant Reshaping Content Creation",
    category: "AI Chatbots",
    excerpt: "While Baidu's Wenxin Yiyan dominates search integration and DeepSeek captures the technical elite, ByteDance's Doubao has carved out a different kingdom:...",
    date: '2026-04-02',
    readTime: '15 min read',
    image: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&h=400&fit=crop"
  },
  {
    slug: 'bytedance-ai-gamble-gpu-kingpin-profit-drop',
    title: "ByteDance's AI Obsession: How a 70% Profit Plunge Turned a Social Media Giant Into China's GPU Kingpin",
    category: "AI Trends",
    excerpt: "ByteDance's AI Obsession: How a 70% Profit Plunge Turned a Social Media Giant Into China's GPU Kingpin The company that built its empire on 15-second...",
    date: '2026-04-01',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&h=400&fit=crop"
  },
  {
    slug: 'china-ai-april-infrastructure-2026',
    title: "China's AI Revolution: Education Reform, National Standards, and Ecosystem Breakthroughs in April 2026",
    category: "AI Infrastructure",
    excerpt: "China's AI Revolution: Education Reform, National Standards, and Ecosystem Breakthroughs in April 2026 Shanghai Jiao Tong University launches...",
    date: '2026-04-01',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1685558589023-3297b012d8bc?w=1200&h=600&fit=crop"
  },
  {
    slug: 'minimax-ipo-212-million-users-ai-companion-empire',
    title: "MiniMax Files for IPO: How China's AI Companion Empire Built 212 Million Users and Challenged the Global Social Landscape",
    category: "AI Robotics",
    excerpt: "MiniMax Files for IPO: How China's AI Companion Empire Built 212 Million Users and Challenged the Global Social Landscape MiniMax's Talkie and 星野 apps...",
    date: '2026-04-01',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=1200&h=600&fit=crop"
  },
  {
    slug: 'tars-embodied-intelligence-455-million-brain-club',
    title: "Tars Raises $455M: How China's 'Robot Brain' Startup Cracked the Embodied Intelligence Code",
    category: "AI Robotics",
    excerpt: "Tars Raises $455M: How China's \"Robot Brain\" Startup Cracked the Embodied Intelligence Code Tars' AWE 3.0-powered A1 robot set a Guinness World Record for...",
    date: '2026-04-01',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1567789884554-0b844b597180?w=1200&h=600&fit=crop"
  },
  {
    slug: 'tongyi-qianwen-alibaba',
    title: "Alibaba Tongyi Qianwen: Enterprise AI Powerhouse",
    category: "AI Chatbots",
    excerpt: "While Baidu captured consumer mindshare and DeepSeek shocked the industry with cost efficiency, Alibaba's Tongyi Qianwen has quietly built the most...",
    date: '2026-04-01',
    readTime: '14 min read',
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=400&fit=crop"
  },
  {
    slug: 'wenxin-yiyan-baidu',
    title: "Baidu Wenxin Yiyan: The 300 Million User AI Assistant",
    category: "AI Chatbots",
    excerpt: "When international headlines celebrate DeepSeek's cost efficiency and Kimi's technical innovations, Baidu's Wenxin Yiyan has quietly achieved something equally remarkable: 300 million monthly active users and a $5 billion annual revenue run rate that makes it one of the most valuable AI products on Earth.",
    date: '2026-04-01',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=1200&h=600&fit=crop"
  },
  {
    slug: 'ai-video-tools-china',
    title: "Chinese AI Video Generation: Kling, Vidu, Hailuo vs Sora Technical Comparison",
    category: "AI Video",
    excerpt: "While OpenAI's Sora captured global attention with its demonstration videos, Chinese companies have been quietly building video generation tools that are...",
    date: '2026-03-31',
    readTime: '15 min read',
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&h=400&fit=crop"
  },
  {
    slug: 'chinese-ai-index-2026',
    title: "The Chinese AI Index 2026: Mapping 103 Companies That Are Reshaping Global Technology",
    category: "Market Intelligence",
    excerpt: "The Chinese AI Index 2026: Mapping 103 Companies That Are Reshaping Global Technology Photo by Joshua Sortino on Unsplash In March 2026, something changed...",
    date: '2026-03-31',
    readTime: '18 min read',
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&q=80"
  },
  {
    slug: 'deepseek-v3-deep-dive',
    title: "DeepSeek-V3: The $5.6M Training Run",
    category: "Technical Analysis",
    excerpt: "DeepSeek-V3 represents one of the most significant efficiency breakthroughs in AI history. Training a model competitive with GPT-4 for just $5.6 million...",
    date: '2026-03-31',
    readTime: '15 min read',
    image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&h=400&fit=crop"
  },
  {
    slug: 'minimax-talkie',
    title: "MiniMax: The 212 Million User AI Companion Empire Built on Digital Intimacy",
    category: "AI Chatbots",
    excerpt: "While ByteDance's Doubao dominates content creation and DeepSeek captures the technical elite, MiniMax has built something arguably more intimate: 212...",
    date: '2026-03-31',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1764664281860-c5725fafa634?w=800&h=400&fit=crop"
  },
  {
    slug: 'chinese-ai-landscape',
    title: "The Rise of Chinese AI: Complete Ecosystem Map (Foundation to Application)",
    category: "Market Intelligence",
    excerpt: "China's AI ecosystem has evolved from a fragmented collection of research labs into a comprehensive industrial stack that rivals Silicon Valley....",
    date: '2026-03-30',
    readTime: '15 min read',
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&h=400&fit=crop"
  },
  {
    slug: 'kimi-2m-context',
    title: "Kimi K2.5 Technical Analysis: 1 Trillion Parameters, 256K Context, Agent Swarms",
    category: "AI Chatbots",
    excerpt: "When Cursor announced that Composer 2.0 was built on Kimi K2.5 rather than GPT-4 or Claude, the message was clear: Chinese foundation models had reached...",
    date: '2026-03-30',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&h=400&fit=crop"
  }
]

export { allPosts }
