// AI in China - Posts Metadata
// 文章元数据管理文件
// ⚠️ AUTO-GENERATED by scripts/sync-metadata.js — DO NOT EDIT MANUALLY

const allPosts = [
  {
    slug: 'ai-interview-coaching-china-graduates-job-market-2026',
    title: "AI Interview Coaching: How Chinese Graduates Are Using AI to Crack the Job Market (+120% Trend Explosion)",
    category: "AI",
    excerpt: "With Xiaohongshu views surging 120% in one week, AI interview coaching has become the hottest trend among Chinese graduates facing a brutal job market. We analyze 6 platforms, university adoption programs, and the DeepSeek-V3 technology powering this revolution.",
    date: '2026-06-03',
    readTime: '16 min read'
  },
  {
    slug: 'minimax-300m-users-arr-doubles-a-share-ipo-china-ai-export-2026',
    title: "MiniMax Hits 300M Users and Doubles ARR in 60 Days: The Anatomy of China's Most Successful AI Export",
    category: "AI",
    excerpt: "In 60 days, MiniMax doubled its annual recurring revenue to approximately $300M, crossed 300 million global users, and launched its A-share IPO process. With 73% of revenue from international markets, the company has built the most successful Chinese AI export since TikTok—and the financials reveal both extraordinary growth and a brutal path to profitability.",
    date: '2026-06-02',
    readTime: '16 min read'
  },
  {
    slug: 'china-ai-drama-revolution-bytedance-650m-empire-2026',
    title: "China's AI Drama Revolution: How ByteDance Built a $650M Short-Content Empire in 90 Days",
    category: "AI",
    excerpt: "In 90 days, China's AI short drama market expanded sixfold from $100M to $650M. ByteDance's integrated ecosystem—Doubao for scripts, Jimeng for visuals, Volcano Engine for compute, and Red Fruit for distribution—has compressed production cycles from 90 days to 7-10 days at 20% of traditional cost. With 150M overseas active users and nearly 50% willing to pay, this is China's most explosive AI content revolution yet.",
    date: '2026-06-01',
    readTime: '16 min read'
  },
  {
    slug: 'china-humanoid-robot-tsunami-2026-50k-units-global-dominance',
    title: "China's Humanoid Robot Tsunami: 50,000 Units, 700% Growth, and Why 2026 Is the Year Everything Changed",
    category: "Embodied AI",
    excerpt: "",
    date: '2026-05-31',
    readTime: '16 min read'
  },
  {
    slug: 'alibaba-zhenwu-m890-ai-chip-china-silicon-sovereignty',
    title: "Alibaba's Zhenwu M890: The 3x AI Chip That Just Shipped 560,000 Units and Rewrote China's Silicon Playbook",
    category: "AI Infrastructure",
    excerpt: "Alibaba's T-Head unveiled the Zhenwu M890 AI chip with 3x performance, 144GB HBM, and 800GB/s interconnect. With 560,000 units already shipped to 400+ customers, this is how China is building an AI chip empire without NVIDIA.",
    date: '2026-05-30',
    readTime: '17 min read'
  },
  {
    slug: 'china-ai-inflection-point-may-2026',
    title: "China's AI Inflection Point: From Burn Rate to Revenue Rate (2026)",
    category: "AI",
    excerpt: "May 2026 delivered the clearest signal yet that China's AI industry has shifted from a cash-burning sprint to a revenue-generating marathon. DeepSeek accepted its first external funding, Alibaba reported AI revenue exceeding 50% of total cloud income, and ByteDance committed $23 billion to infrastructure. Here's the full breakdown.",
    date: '2026-05-29',
    readTime: '16 min read'
  },
  {
    slug: 'china-ai-models-dominate-global-api-traffic-token-export-2026',
    title: "China's AI Models Dominate Global API Traffic: The Token Export Boom Silicon Valley Didn't See Coming",
    category: "AI Business",
    excerpt: "Chinese AI models now consume 61% of top-tier global API token volume. MiniMax M2.5 alone processes 5 trillion tokens weekly on OpenRouter — more than GPT-5.5 and Claude 4 combined. Here's how China's 'token export' economy became the invisible infrastructure powering developers worldwide.",
    date: '2026-05-28',
    readTime: '17 min read'
  },
  {
    slug: 'china-ai-fraud-epidemic-deepfake-panic-2026',
    title: "China's AI Fraud Epidemic: Inside the 5.6 Billion View Deepfake Panic Reshaping Digital Trust",
    category: "AI Security",
    excerpt: "",
    date: '2026-05-27',
    readTime: '16 min read'
  },
  {
    slug: 'ai-digital-humans-china-billion-dollar-livestream-revolution',
    title: "China's AI Digital Human Explosion: The 100 Billion Yuan Avatar Economy Reshaping E-Commerce",
    category: "AI Video",
    excerpt: "",
    date: '2026-05-26',
    readTime: '16 min read'
  },
  {
    slug: 'china-ai-unicorn-stampede-kimi-deepseek-valuation-shakeout-2026-26',
    title: "China's AI Unicorn Stampede: Kimi's $20B Round, DeepSeek's $500B Valuation, and the Great Model Shakeout of 2026",
    category: "AI",
    excerpt: "",
    date: '2026-05-26',
    readTime: '16 min read'
  },
  {
    slug: 'deepseek-permanent-75-percent-api-price-cut-ai-war-2026',
    title: "DeepSeek's Permanent 75% Price Cut: The API War That Just Changed Everything",
    category: "AI Infrastructure",
    excerpt: "On May 22, DeepSeek made its 2.5 discount permanent. At $0.025 per million cached tokens, the company's API pricing isn't just cheap — it's a declaration that inference cost is heading toward zero, and every competitor must now adapt or die.",
    date: '2026-05-25',
    readTime: '16 min read'
  },
  {
    slug: 'china-storage-twin-giants-ipo-ai-compute-2026',
    title: "China's Storage Twin Giants Race to IPO: A $500B Revaluation of the AI Compute Foundation",
    category: "AI Infrastructure",
    excerpt: "Changxin Technology and Yangtze Memory Technologies, China's two storage chip giants, are both charging toward IPO. With combined Q1 revenue exceeding $10B and a $500B+ market opportunity ahead, this is the moment China's semiconductor industry goes from 'domestic replacement' to 'global pricing power.'",
    date: '2026-05-24',
    readTime: '16 min read'
  },
  {
    slug: 'china-embodied-intelligence-infrastructure-ndrc-robots-factories-malls-homes',
    title: "China's Embodied Intelligence Infrastructure Push: NDRC Unveils National Plan to Put Robots in Factories, Malls, and Homes",
    category: "AI Policy & Infrastructure",
    excerpt: "China's NDRC just announced a national infrastructure plan for embodied intelligence, with dedicated training bases, 'big brain/small brain' model architecture, and a roadmap to deploy robots across factories, shopping malls, and homes by 2027.",
    date: '2026-05-23',
    readTime: '16 min read'
  },
  {
    slug: 'huawei-pangu-ultra-moe-718b-chinese-silicon',
    title: "Huawei Pangu Ultra MoE: The 718-Billion-Parameter Model Built Entirely on Chinese Silicon",
    category: "AI Infrastructure",
    excerpt: "Huawei's Pangu Ultra MoE packs 718 billion parameters and was trained end-to-end on Ascend AI chips. Here's why this milestone proves China no longer needs NVIDIA to build world-class large language models.",
    date: '2026-05-22',
    readTime: '16 min read'
  },
  {
    slug: 'china-ai-global-expansion-minimax-2-billion-users-2026',
    title: "China AI Goes Global: How MiniMax Built a 236 Million User Empire from Shanghai",
    category: "AI Trends",
    excerpt: "",
    date: '2026-05-21',
    readTime: '16 min read'
  },
  {
    slug: 'china-ai-interview-revolution-2026',
    title: "AI Interview Coaching: China's 2026 Grad Job Market Hack",
    category: "AI Trends",
    excerpt: "",
    date: '2026-05-20',
    readTime: '16 min read'
  },
  {
    slug: 'china-ai-chip-renaissance-q1-2026',
    title: "China's AI Chip Renaissance: The Quarter That Changed Everything",
    category: "AI Infrastructure",
    excerpt: "",
    date: '2026-05-19',
    readTime: '16 min read'
  },
  {
    slug: 'china-ai-ppt-revolution-3-minute-decks-2026',
    title: "The 3-Minute Deck Revolution: How China's Office Workers Are Using AI to Replace PowerPoint Design",
    category: "AI Applications",
    excerpt: "",
    date: '2026-05-18',
    readTime: '16 min read'
  },
  {
    slug: 'china-ai-hallucination-blind-spot-crisis-2026',
    title: "The Hallucination Blind Spot: How China's 249M AI Users Became Perfect Prey for a Deception Epidemic",
    category: "AI Safety",
    excerpt: "",
    date: '2026-05-17',
    readTime: '16 min read'
  },
  {
    slug: 'china-ai-creator-economy-digital-humans-2026',
    title: "China's AI Creator Economy: How Digital Humans and $45B Valuations Are Reshaping Global Content",
    category: "AI Applications",
    excerpt: "",
    date: '2026-05-16',
    readTime: '16 min read'
  },
  {
    slug: 'china-ai-capital-war-deepseek-kimi-funding-2026',
    title: "China's AI Capital War: DeepSeek Hits $50B, Kimi Raises $2B in Historic Funding Frenzy",
    category: "Market Intelligence",
    excerpt: "",
    date: '2026-05-15',
    readTime: '17 min read'
  },
  {
    slug: 'china-ai-invisible-empire-consumer-apps-2026',
    title: "The Invisible Empire: How China's AI Consumer Apps Quietly Conquered 2.5 Billion Users — And Why the World Barely Noticed",
    category: "AI Business",
    excerpt: "",
    date: '2026-05-13',
    readTime: '16 min read'
  },
  {
    slug: 'china-six-networks-trillion-infrastructure-ai-compute-2026',
    title: "China's $7 Trillion 'Six Networks' Strategy: When AI Compute Gets the Same Priority as Water and Electricity",
    category: "AI Policy",
    excerpt: "",
    date: '2026-05-13',
    readTime: '17 min read'
  },
  {
    slug: 'china-ai-olympus-65-billion-war-future-intelligence-2026',
    title: "China's AI Olympus: The $65 Billion War for the Future of Intelligence",
    category: "AI",
    excerpt: "",
    date: '2026-05-11',
    readTime: '16 min read'
  },
  {
    slug: 'deepseek-73b-megaround-china-ai-funding-frenzy-2026',
    title: "DeepSeek's $7.3B Mega-Round: China's AI Funding Frenzy Hits Historic Heights",
    category: "AI",
    excerpt: "",
    date: '2026-05-10',
    readTime: '16 min read'
  },
  {
    slug: 'china-agent-era-national-policy-ai-terminal-standards-anthropic-trillion-2026',
    title: "China's Agent Era Begins: National Policy Framework, AI Terminal Standards, and the Trillion-Dollar Global AI Race",
    category: "AI",
    excerpt: "",
    date: '2026-05-09',
    readTime: '16 min read'
  },
  {
    slug: 'china-ai-infrastructure-awakening-wuwenxinqiong-deepseek-multimodal-2026',
    title: "China's AI Infrastructure Awakens: Wuwenxinqiong's $100M Bet and the Full-Stack Race to Support 8 Trillion Tokens",
    category: "AI Infrastructure",
    excerpt: "Wuwenxinqiong raised $100M+ to build China's AI-native infrastructure. DeepSeek launched multimodal capabilities. Alibaba deployed voice-first PC AI. And China's models processed 8 trillion tokens in a week—surpassing the US for the third consecutive time. The foundation layer is finally catching up to the model layer.",
    date: '2026-05-08',
    readTime: '17 min read'
  },
  {
    slug: 'doubao-charging-ai-free-era-ends-china-2026',
    title: "Doubao Starts Charging: How China's Biggest AI App Ended the Free Era — and What It Means for 345 Million Users",
    category: "AI Business",
    excerpt: "ByteDance's Doubao, China's largest AI app with 345M MAU, just launched paid tiers from $9.50 to $72/month. Here's why 120 trillion daily tokens made free unsustainable, and what this signals for the global AI industry.",
    date: '2026-05-07',
    readTime: '16 min read'
  },
  {
    slug: 'kimi-20-billion-valuation-china-ai-token-economy',
    title: "Kimi's $20 Billion Bet: How China's AI Token Economy Is Rewriting Global Power Dynamics",
    category: "AI Industry",
    excerpt: "Kimi hits a $20 billion funding round at $200 billion valuation while China's AI token consumption surges past the US for the third time. Here's what it means for the global AI landscape.",
    date: '2026-05-07',
    readTime: '16 min read'
  },
  {
    slug: 'china-embodied-intelligence-revolution-2026',
    title: "China's Embodied Intelligence Revolution: How 230+ Companies and a $110 Billion Market Are Reshaping Global Robotics in 2026",
    category: "AI Infrastructure",
    excerpt: "China's embodied intelligence industry is surging from 1,800 humanoid robots shipped in 2025 to an anticipated 100,000+ in 2026, backed by $195 billion in annual funding and a supply chain that cuts costs to 50% of Western equivalents.",
    date: '2026-05-06',
    readTime: '16 min read'
  },
  {
    slug: 'deepseek-v4-promo-ending-analysis',
    title: "DeepSeek V4's 75% Promo Ends May 31: What Happens Next and Why the AI Pricing War Is Just Beginning",
    category: "AI Infrastructure",
    excerpt: "",
    date: '2026-05-05',
    readTime: '16 min read'
  },
  {
    slug: 'china-ai-deepfake-fraud-crisis-2026',
    title: "China's AI Deepfake Fraud Crisis: How 700,000 Annual Scams and a $40 Billion Global Threat Are Reshaping Trust in the Digital Age",
    category: "AI Safety",
    excerpt: "",
    date: '2026-05-03',
    readTime: '16 min read'
  },
  {
    slug: 'china-ai-revolution-may-2026-tokens-deepseek-huawei',
    title: "China's AI Revolution: How 140 Trillion Tokens, DeepSeek V4 on Huawei Chips, and a $700B Arms Race Are Reshaping Global Technology",
    category: "AI Infrastructure",
    excerpt: "",
    date: '2026-05-03',
    readTime: '16 min read'
  },
  {
    slug: 'kimi-k2-6-open-source-coding-revolution',
    title: "Kimi K2.6: How a $18B Chinese Startup Is Rewriting the Rules of Open-Source AI Coding",
    category: "AI Infrastructure",
    excerpt: "",
    date: '2026-05-02',
    readTime: '16 min read'
  },
  {
    slug: 'china-ai-global-surge-api-traffic-empire-2026',
    title: "From Made in China to Trained in China: The Untold Story of How Chinese AI Conquered Global Developers",
    category: "AI Industry",
    excerpt: "",
    date: '2026-05-01',
    readTime: '17 min read'
  },
  {
    slug: 'china-ai-agent-revolution-2026-policy-market',
    title: "Inside China's AI Policy Machine: How the Politburo's 'AI+ Action' Directive Is Rewriting Procurement Law",
    category: "AI Policy",
    excerpt: "",
    date: '2026-04-30',
    readTime: '17 min read'
  },
  {
    slug: 'deepseek-v4-pricing-strategy-analysis',
    title: "DeepSeek V4 Pricing Strategy: How $0.14/1M Tokens Is Reshaping the Economics of Frontier AI",
    category: "AI Infrastructure",
    excerpt: "",
    date: '2026-04-30',
    readTime: '16 min read'
  },
  {
    slug: 'ai-compute-crunch-china-token-crisis-2026',
    title: "The Great AI Compute Crunch: How China's AI Boom Is Running Out of Tokens",
    category: "AI Infrastructure",
    excerpt: "",
    date: '2026-04-29',
    readTime: '17 min read'
  },
  {
    slug: 'bytedance-seed-brain-drain-70-engineers',
    title: "ByteDance's AI Brain Drain: 70 Top Engineers Exit Seed Team in 12 Months",
    category: "AI Trends",
    excerpt: "",
    date: '2026-04-28',
    readTime: '15 min read'
  },
  {
    slug: 'deepseek-v4-million-token-china-ai-sovereignty',
    title: "DeepSeek V4: The Million-Token API Update That Signals China's AI Sovereignty Shift",
    category: "AI Infrastructure",
    excerpt: "",
    date: '2026-04-22',
    readTime: '17 min read'
  },
  {
    slug: 'china-embodied-intelligence-robot-marathon-2026',
    title: "China's Embodied Intelligence Revolution: When Robots Outrun Humans — April 2026",
    category: "AI Trends",
    excerpt: "",
    date: '2026-04-21',
    readTime: '18 min read'
  },
  {
    slug: 'deepseek-first-funding-20-billion-valuation',
    title: "DeepSeek Breaks Its Vow: Inside the $3 Billion Funding Round That Shook China's AI World",
    category: "AI Infrastructure",
    excerpt: "",
    date: '2026-04-20',
    readTime: '15 min read'
  },
  {
    slug: 'china-ai-avatar-revolution-2026',
    title: "China's AI Avatar Revolution: How 410 Million Views Signal a Global Content Creation Shift",
    category: "AI Industry",
    excerpt: "",
    date: '2026-04-18',
    readTime: '16 min read'
  },
  {
    slug: 'stanford-ai-index-2026-china-rise',
    title: "Stanford AI Index 2026: China's 'Parallel Run' Era Has Arrived",
    category: "AI Trends",
    excerpt: "",
    date: '2026-04-17',
    readTime: '16 min read'
  },
  {
    slug: 'alibaba-token-hub-100b-gambit',
    title: "Alibaba's $100B Token Gambit: Inside the Alibaba Token Hub Revolution Reshaping China's AI Economy",
    category: "AI Trends",
    excerpt: "",
    date: '2026-04-16',
    readTime: '17 min'
  },
  {
    slug: 'china-ai-agent-explosion-2025-enterprise-deployment',
    title: "China's AI Agent Explosion: How 126 Platforms and $1B+ in Enterprise Deals Are Reshaping Global Automation",
    category: "AI Trends",
    excerpt: "",
    date: '2026-04-15',
    readTime: '16 min read'
  },
  {
    slug: 'china-ai-model-war-april-2026-week-changed-everything',
    title: "The Week That Changed Everything: China's AI Model War Intensifies in April 2026",
    category: "AI Trends",
    excerpt: "",
    date: '2026-04-13',
    readTime: '17 min read'
  },
  {
    slug: 'china-ai-chip-war-2026-us-sanctions',
    title: "The Great Silicon Wall: How China's AI Industry Is Defying U.S. Chip Sanctions in 2026",
    category: "AI Infrastructure",
    excerpt: "",
    date: '2026-04-12',
    readTime: '17 min read'
  },
  {
    slug: 'china-ai-model-wars-april-2026',
    title: "China's AI Model Wars: How Alibaba, ByteDance, and MiniMax Are Reshaping Global AI Competition in April 2026",
    category: "AI Trends",
    excerpt: "",
    date: '2026-04-11',
    readTime: '18 min read'
  },
  {
    slug: 'modelbest-edge-ai-unicorn-2026',
    title: "ModelBest Becomes Unicorn: How Tsinghua's Edge AI Pioneer Is Reshaping On-Device Intelligence",
    category: "AI Trends",
    excerpt: "",
    date: '2026-04-10',
    readTime: '17 min'
  },
  {
    slug: 'ai-interview-coaching-china-2025',
    title: "The AI Interview Coach Phenomenon: How Chinese Graduates Are Using AI to Crack the Job Market",
    category: "AI Trends",
    excerpt: "",
    date: '2026-04-08',
    readTime: '16 min'
  },
  {
    slug: 'china-ai-token-surge-gen-z',
    title: "China's AI Overtake: 31% Surge in Token Usage Signals Global Power Shift",
    category: "AI Trends",
    excerpt: "",
    date: '2026-04-07',
    readTime: '17 min read'
  },
  {
    slug: 'china-ai-avatar-revolution-2025',
    title: "China's AI Avatar Revolution: 410M Views Transformed Content Creation Forever",
    category: "AI Trends",
    excerpt: "",
    date: '2026-04-05',
    readTime: '16 min read'
  },
  {
    slug: 'china-ai-digital-human-revolution',
    title: "China's AI Digital Human Revolution: 80,000 Virtual Avatars Reshaping Content",
    category: "AI Applications",
    excerpt: "",
    date: '2026-04-05',
    readTime: '16 min read'
  },
  {
    slug: 'doubao-12-trillion-token-explosion',
    title: "Doubao's 12 Trillion Token Explosion: How ByteDance Is Quietly Winning the Global AI Race",
    category: "AI Infrastructure",
    excerpt: "",
    date: '2026-04-04',
    readTime: '10 min read'
  },
  {
    slug: 'stepfun-terminal-ai-revolution',
    title: "StepFun's $7 Billion Bet: How China's AI Unicorn Is Winning the Terminal Race",
    category: "AI Infrastructure",
    excerpt: "",
    date: '2026-04-03',
    readTime: '10 min read'
  },
  {
    slug: 'ai-thesis-writing-china',
    title: "AI Thesis Writing Explodes: How 12 Million Chinese Students Are Rewriting Academic Rules",
    category: "AI Chatbots",
    excerpt: "",
    date: '2026-04-02',
    readTime: '16 min read'
  },
  {
    slug: 'doubao-bytedance',
    title: "ByteDance Doubao: The 200 Million User AI Assistant Reshaping Content Creation",
    category: "AI Chatbots",
    excerpt: "",
    date: '2026-04-02',
    readTime: '15 min read'
  },
  {
    slug: 'bytedance-ai-gamble-gpu-kingpin-profit-drop',
    title: "ByteDance's AI Obsession: How a 70% Profit Plunge Turned a Social Media Giant Into China's GPU Kingpin",
    category: "AI Trends",
    excerpt: "",
    date: '2026-04-01',
    readTime: '16 min read'
  },
  {
    slug: 'china-ai-april-infrastructure-2026',
    title: "China's AI Revolution: Education Reform, National Standards, and Ecosystem Breakthroughs in April 2026",
    category: "AI Infrastructure",
    excerpt: "",
    date: '2026-04-01',
    readTime: '16 min read'
  },
  {
    slug: 'minimax-ipo-212-million-users-ai-companion-empire',
    title: "MiniMax Files for IPO: How China's AI Companion Empire Built 212 Million Users and Challenged the Global Social Landscape",
    category: "AI Robotics",
    excerpt: "",
    date: '2026-04-01',
    readTime: '16 min read'
  },
  {
    slug: 'tars-embodied-intelligence-455-million-brain-club',
    title: "Tars Raises $455M: How China's 'Robot Brain' Startup Cracked the Embodied Intelligence Code",
    category: "AI Robotics",
    excerpt: "",
    date: '2026-04-01',
    readTime: '16 min read'
  },
  {
    slug: 'tongyi-qianwen-alibaba',
    title: "Alibaba Tongyi Qianwen: Enterprise AI Powerhouse",
    category: "AI Chatbots",
    excerpt: "",
    date: '2026-04-01',
    readTime: '14 min read'
  },
  {
    slug: 'wenxin-yiyan-baidu',
    title: "Baidu Wenxin Yiyan: The 300 Million User AI Assistant",
    category: "AI Chatbots",
    excerpt: "",
    date: '2026-04-01',
    readTime: '14 min read'
  },
  {
    slug: 'ai-video-tools-china',
    title: "Chinese AI Video Generation: Kling, Vidu, Hailuo vs Sora Technical Comparison",
    category: "AI Video",
    excerpt: "",
    date: '2026-03-31',
    readTime: '15 min read'
  },
  {
    slug: 'chinese-ai-index-2026',
    title: "Chinese AI Index: 103 Companies Tracking",
    category: "Market Intelligence",
    excerpt: "",
    date: '2026-03-31',
    readTime: '12 min read'
  },
  {
    slug: 'deepseek-v3-deep-dive',
    title: "DeepSeek-V3: The $5.6M Training Run",
    category: "Technical Analysis",
    excerpt: "",
    date: '2026-03-31',
    readTime: '15 min read'
  },
  {
    slug: 'deepseek-vs-chatgpt',
    title: "DeepSeek vs ChatGPT: Complete Comparison",
    category: "AI Chatbots",
    excerpt: "",
    date: '2026-03-31',
    readTime: '10 min read'
  },
  {
    slug: 'minimax-talkie',
    title: "MiniMax: The 212 Million User AI Companion Empire Built on Digital Intimacy",
    category: "AI Chatbots",
    excerpt: "",
    date: '2026-03-31',
    readTime: '16 min read'
  },
  {
    slug: 'chinese-ai-landscape',
    title: "The Rise of Chinese AI: Complete Ecosystem Map (Foundation to Application)",
    category: "Market Intelligence",
    excerpt: "",
    date: '2026-03-30',
    readTime: '20 min read'
  },
  {
    slug: 'kimi-2m-context',
    title: "Kimi K2.5 Technical Analysis: 1 Trillion Parameters, 256K Context, Agent Swarms",
    category: "AI Chatbots",
    excerpt: "",
    date: '2026-03-30',
    readTime: '16 min read'
  }
]

export { allPosts }
