// AI in China - Posts Metadata
// 文章元数据管理文件
// ⚠️ AUTO-GENERATED by scripts/sync-metadata.js — DO NOT EDIT MANUALLY
// Generated: 2026-06-06T20:17:31.247Z

const allPosts = [
  {
    slug: 'tencent-wechat-ai-agent-billion-users-china-2026',
    title: "Tencent's WeChat AI Agent: The 1.4 Billion-User Bet That Reshaped China's Tech Markets Overnight",
    category: "AI",
    excerpt: "A Financial Times report on June 2 revealed Tencent is testing an AI agent inside WeChat. The result: a $41 billion market cap surge, China's biggest agentic AI platform, and a direct challenge to Alibaba and ByteDance.",
    date: '2026-06-07',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=1200"
  },
  {
    slug: 'china-ai-june-surge-deepseek-zhipu-agentic-ai-2026',
    title: "China's AI June Surge: DeepSeek's $7B First Round, Zhipu's STAR Market Bid, and the Agentic AI Stack",
    category: "AI",
    excerpt: "DeepSeek closes its first external round at $59B. Zhipu files for a $2B STAR Market IPO. Huawei unveils an Agentic AI stack. And on June 6, China's AI industry converges on Hangzhou for a summit that signals the shift from 'model hype' to 'industrial deployment.'",
    date: '2026-06-06',
    readTime: '17 min read',
    image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=1200"
  },
  {
    slug: 'deepseek-7-billion-fundraising-tencent-catl-api-price-war-2026',
    title: "DeepSeek's $7.4B Fundraising Frenzy: How 500 Billion Yuan, Tencent's Bet, and a 97.5% API Price Collapse Are Rewriting China's AI Rules",
    category: "Market Intelligence",
    excerpt: "While Silicon Valley fixates on Anthropic's $96.5 billion valuation and its secret IPO filing, something equally seismic is unfolding in China. DeepSeek—the startup that taught the world that $5.6...",
    date: '2026-06-05',
    readTime: '17 min read',
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&h=400&fit=crop"
  },
  {
    slug: 'china-ai-ipo-wave-zhipu-minimax-2026',
    title: "China's AI IPO Wave: How Zhipu and MiniMax Are Rewriting the Rules of AI Capitalization",
    category: "AI",
    excerpt: "Something historic is happening in China's AI industry. Zhipu AI, one of China's \"Big Five\" large model companies, has seen its share price surge over 1,600% since its Hong Kong IPO, pushing its...",
    date: '2026-06-04',
    readTime: '16 min',
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=1200&h=600&fit=crop"
  },
  {
    slug: 'ai-interview-coaching-china-graduates-job-market-2026',
    title: "AI Interview Coaching: How Chinese Graduates Are Using AI to Crack the Job Market (+120% Trend Explosion)",
    category: "AI",
    excerpt: "With Xiaohongshu views surging 120% in one week, AI interview coaching has become the hottest trend among Chinese graduates facing a brutal job market. We analyze 6 platforms, university adoption programs, and the DeepSeek-V3 technology powering this revolution.",
    date: '2026-06-03',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=1200&q=80"
  },
  {
    slug: 'china-ai-agent-era-140-trillion-tokens-2026',
    title: "China's AI Agent Era: How 140 Trillion Daily Tokens, New Regulations, and a DeepSeek Price War Are Reshaping Global AI",
    category: "AI Industry",
    excerpt: "On June 1, 2026, three Chinese ministries jointly issued the \"Implementation Opinions on Standardized Application and Innovative Development of AI Agents\" — the most comprehensive national policy...",
    date: '2026-06-03',
    readTime: '17 min read',
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1200&h=600&fit=crop"
  },
  {
    slug: 'deepseek-7b-mega-round-china-ai-capital-shift-2026',
    title: "DeepSeek's $7.4B Mega-Round: How China's Most Secretive AI Lab Went All-In on Capital",
    category: "AI Infrastructure",
    excerpt: "DeepSeek — the company that built a $5.6M model to rival GPT-4 and rejected venture capital for two years — is now raising $7.4 billion in the largest AI funding round in Chinese history. Founder Liang Wenfeng is putting $2.8 billion of his own money on the table. Tencent commits $1.4 billion. CATL invests $700 million. And the valuation? A staggering $52-59 billion.",
    date: '2026-06-03',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1639322537228-f710d846310a?w=1200&h=600&fit=crop"
  },
  {
    slug: 'minimax-300m-users-arr-doubles-a-share-ipo-china-ai-export-2026',
    title: "MiniMax Hits 300M Users and Doubles ARR in 60 Days: The Anatomy of China's Most Successful AI Export",
    category: "AI",
    excerpt: "In 60 days, MiniMax doubled its annual recurring revenue to approximately $300M, crossed 300 million global users, and launched its A-share IPO process. With 73% of revenue from international markets, the company has built the most successful Chinese AI export since TikTok—and the financials reveal both extraordinary growth and a brutal path to profitability.",
    date: '2026-06-02',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=1200&q=80"
  },
  {
    slug: 'china-ai-drama-revolution-bytedance-650m-empire-2026',
    title: "China's AI Drama Revolution: How ByteDance Built a $650M Short-Content Empire in 90 Days",
    category: "AI",
    excerpt: "In 90 days, China's AI short drama market expanded sixfold from $100M to $650M. ByteDance's integrated ecosystem—Doubao for scripts, Jimeng for visuals, Volcano Engine for compute, and Red Fruit for distribution—has compressed production cycles from 90 days to 7-10 days at 20% of traditional cost. With 150M overseas active users and nearly 50% willing to pay, this is China's most explosive AI content revolution yet.",
    date: '2026-06-01',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1200&q=80"
  },
  {
    slug: 'china-humanoid-robot-tsunami-2026-50k-units-global-dominance',
    title: "China's Humanoid Robot Tsunami: 50,000 Units, 700% Growth, and Why 2026 Is the Year Everything Changed",
    category: "Embodied AI",
    excerpt: "In May 2026, three separate research reports dropped within two weeks of each other. Each told the same story in slightly different numbers, but the narrative was unmistakable: the humanoid robot...",
    date: '2026-05-31',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1676299081847-824916de030a?w=1200&h=600&fit=crop"
  },
  {
    slug: 'alibaba-zhenwu-m890-ai-chip-china-silicon-sovereignty',
    title: "Alibaba's Zhenwu M890: The 3x AI Chip That Just Shipped 560,000 Units and Rewrote China's Silicon Playbook",
    category: "AI Infrastructure",
    excerpt: "Alibaba's T-Head unveiled the Zhenwu M890 AI chip with 3x performance, 144GB HBM, and 800GB/s interconnect. With 560,000 units already shipped to 400+ customers, this is how China is building an AI chip empire without NVIDIA.",
    date: '2026-05-30',
    readTime: '17 min read',
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200"
  },
  {
    slug: 'china-ai-inflection-point-may-2026',
    title: "China's AI Inflection Point: From Burn Rate to Revenue Rate (2026)",
    category: "AI",
    excerpt: "May 2026 delivered the clearest signal yet that China's AI industry has shifted from a cash-burning sprint to a revenue-generating marathon. DeepSeek accepted its first external funding, Alibaba reported AI revenue exceeding 50% of total cloud income, and ByteDance committed $23 billion to infrastructure. Here's the full breakdown.",
    date: '2026-05-29',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200&q=80"
  },
  {
    slug: 'china-ai-models-dominate-global-api-traffic-token-export-2026',
    title: "China's AI Models Dominate Global API Traffic: The Token Export Boom Silicon Valley Didn't See Coming",
    category: "AI Business",
    excerpt: "Chinese AI models now consume 61% of top-tier global API token volume. MiniMax M2.5 alone processes 5 trillion tokens weekly on OpenRouter — more than GPT-5.5 and Claude 4 combined. Here's how China's 'token export' economy became the invisible infrastructure powering developers worldwide.",
    date: '2026-05-28',
    readTime: '17 min read',
    image: "https://images.unsplash.com/photo-1535378437327-b71042e1da31?w=1200&h=600&fit=crop"
  },
  {
    slug: 'china-ai-fraud-epidemic-deepfake-panic-2026',
    title: "China's AI Fraud Epidemic: Inside the 5.6 Billion View Deepfake Panic Reshaping Digital Trust",
    category: "AI Security",
    excerpt: "A 62-year-old retired teacher in Hangzhou lost ¥280,000 to an AI deepfake video call from her 'son.' The story sparked a national conversation reaching 5.6 billion views across Chinese social media — the fastest-growing AI topic at +300% week-over-week. What began as scattered fraud reports has crystallized into a full-blown public anxiety crisis, forcing regulators and AI companies into an unprecedented response.",
    date: '2026-05-27',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=1200&h=600&fit=crop"
  },
  {
    slug: 'ai-digital-humans-china-billion-dollar-livestream-revolution',
    title: "China's AI Digital Human Explosion: The 100 Billion Yuan Avatar Economy Reshaping E-Commerce",
    category: "AI Video",
    excerpt: "In February 2026, Chinese regulators drew a hard line: every AI-generated face in a livestream must be labeled. Two months later, that rule hasn't slowed the industry down—it's accelerated it. With...",
    date: '2026-05-26',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&h=400&fit=crop"
  },
  {
    slug: 'china-ai-unicorn-stampede-kimi-deepseek-valuation-shakeout-2026-26',
    title: "China's AI Unicorn Stampede: Kimi's $20B Round, DeepSeek's $500B Valuation, and the Great Model Shakeout of 2026",
    category: "AI",
    excerpt: "One $20 billion funding round. Another $500 billion valuation. Two IPOs with stock prices up 600%. And a single question on every investor's mind: Is China's AI industry about to produce its own NVIDIA? This is the moment China's AI industry transforms from 'copycat' to 'category leader.'",
    date: '2026-05-26',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1523961131990-5ea7c61b2107?w=1200"
  },
  {
    slug: 'deepseek-permanent-75-percent-api-price-cut-ai-war-2026',
    title: "DeepSeek's Permanent 75% Price Cut: The API War That Just Changed Everything",
    category: "AI Infrastructure",
    excerpt: "On May 22, DeepSeek made its 2.5 discount permanent. At $0.025 per million cached tokens, the company's API pricing isn't just cheap — it's a declaration that inference cost is heading toward zero, and every competitor must now adapt or die.",
    date: '2026-05-25',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=1200"
  },
  {
    slug: 'china-storage-twin-giants-ipo-ai-compute-2026',
    title: "China's Storage Twin Giants Race to IPO: A $500B Revaluation of the AI Compute Foundation",
    category: "AI Infrastructure",
    excerpt: "Changxin Technology and Yangtze Memory Technologies, China's two storage chip giants, are both charging toward IPO. With combined Q1 revenue exceeding $10B and a $500B+ market opportunity ahead, this is the moment China's semiconductor industry goes from 'domestic replacement' to 'global pricing power.'",
    date: '2026-05-24',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200"
  },
  {
    slug: 'china-embodied-intelligence-infrastructure-ndrc-robots-factories-malls-homes',
    title: "China's Embodied Intelligence Infrastructure Push: NDRC Unveils National Plan to Put Robots in Factories, Malls, and Homes",
    category: "AI Policy & Infrastructure",
    excerpt: "China's NDRC just announced a national infrastructure plan for embodied intelligence, with dedicated training bases, 'big brain/small brain' model architecture, and a roadmap to deploy robots across factories, shopping malls, and homes by 2027.",
    date: '2026-05-23',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1676299081847-824916de030a?w=1200"
  },
  {
    slug: 'huawei-pangu-ultra-moe-718b-chinese-silicon',
    title: "Huawei Pangu Ultra MoE: The 718-Billion-Parameter Model Built Entirely on Chinese Silicon",
    category: "AI Infrastructure",
    excerpt: "Huawei's Pangu Ultra MoE packs 718 billion parameters and was trained end-to-end on Ascend AI chips. Here's why this milestone proves China no longer needs NVIDIA to build world-class large language models.",
    date: '2026-05-22',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=1200"
  },
  {
    slug: 'china-ai-global-expansion-minimax-2-billion-users-2026',
    title: "China AI Goes Global: How MiniMax Built a 236 Million User Empire from Shanghai",
    category: "AI Trends",
    excerpt: "On March 2, 2026, MiniMax released its first annual report as a publicly traded company — and in doing so, delivered something the global AI industry had never seen: audited financial proof that a...",
    date: '2026-05-21',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1626908013351-800ddd734b8a?w=1200&h=600&fit=crop"
  },
  {
    slug: 'china-ai-interview-revolution-2026',
    title: "AI Interview Coaching: China's 2026 Grad Job Market Hack",
    category: "AI Trends",
    excerpt: "In the seven days leading up to May 20, 2026, Chinese social media platform Xiaohongshu recorded a 120% week-over-week surge in searches for \"AI interview coaching\" (AI面试辅导). The topic accumulated...",
    date: '2026-05-20',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1523961131990-5ea7c61b2107?w=1200&h=600&fit=crop"
  },
  {
    slug: 'china-ai-chip-renaissance-q1-2026',
    title: "China's AI Chip Renaissance: The Quarter That Changed Everything",
    category: "AI Infrastructure",
    excerpt: "For years, China's AI chip industry was defined by what it couldn't do. Couldn't access the most advanced manufacturing. Couldn't match Nvidia's software ecosystem. Couldn't turn a profit. The...",
    date: '2026-05-19',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1592659762303-90081d34b277?w=1200&h=600&fit=crop"
  },
  {
    slug: 'china-ai-ppt-revolution-3-minute-decks-2026',
    title: "The 3-Minute Deck Revolution: How China's Office Workers Are Using AI to Replace PowerPoint Design",
    category: "AI Applications",
    excerpt: "The 3-Minute Deck Revolution: How China's Office Workers Are Using AI to Replace PowerPoint Design",
    date: '2026-05-18',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1644088379091-d574269d422f?w=1200&h=600&fit=crop"
  },
  {
    slug: 'china-ai-hallucination-blind-spot-crisis-2026',
    title: "The Hallucination Blind Spot: How China's 249M AI Users Became Perfect Prey for a Deception Epidemic",
    category: "AI Safety",
    excerpt: "China's generative AI adoption has reached a scale unmatched by any nation: 249 million users—17.7% of the population—now interact with large language models regularly. But beneath this milestone...",
    date: '2026-05-17',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?w=1200&h=600&fit=crop"
  },
  {
    slug: 'china-ai-creator-economy-digital-humans-2026',
    title: "China's AI Creator Economy: How Digital Humans and $45B Valuations Are Reshaping Global Content",
    category: "AI Applications",
    excerpt: "On May 6, 2026, while Western markets were digesting another quarterly earnings cycle, China's AI industry quietly delivered a one-two punch that reverberated through global venture capital....",
    date: '2026-05-16',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=800&h=400&fit=crop"
  },
  {
    slug: 'china-ai-capital-war-deepseek-kimi-funding-2026',
    title: "China's AI Capital War: DeepSeek Hits $50B, Kimi Raises $2B in Historic Funding Frenzy",
    category: "Market Intelligence",
    excerpt: "> In a single week, China's AI startup valuations jumped by over $100 billion. DeepSeek went from $10B to $50B. Kimi locked in $2B fresh capital. And the entire \"Six Little Tigers\" cohort is racing...",
    date: '2026-05-15',
    readTime: '17 min read',
    image: "https://images.unsplash.com/photo-1551650975-87deedd944c3?w=1200&h=600&fit=crop"
  },
  {
    slug: 'china-ai-invisible-empire-consumer-apps-2026',
    title: "The Invisible Empire: How China's AI Consumer Apps Quietly Conquered 2.5 Billion Users — And Why the World Barely Noticed",
    category: "AI Business",
    excerpt: "While Silicon Valley obsessed over GPT-5's next token and Anthropic's march toward a trillion-dollar valuation, something extraordinary was happening on the other side of the Pacific. China's AI...",
    date: '2026-05-13',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=1200&h=600&fit=crop"
  },
  {
    slug: 'china-six-networks-trillion-infrastructure-ai-compute-2026',
    title: "China's $7 Trillion 'Six Networks' Strategy: When AI Compute Gets the Same Priority as Water and Electricity",
    category: "AI Policy",
    excerpt: "On April 28, 2026, China's Politburo did something unprecedented: it elevated compute networks (算力网) to the same strategic tier as water networks, power grids, and logistics networks. In a single...",
    date: '2026-05-13',
    readTime: '17 min read',
    image: "https://images.unsplash.com/photo-1594915440248-1e419eba6611?w=1200"
  },
  {
    slug: 'china-ai-olympus-65-billion-war-future-intelligence-2026',
    title: "China's AI Olympus: The $65 Billion War for the Future of Intelligence",
    category: "AI",
    excerpt: "In seven days, Chinese AI companies raised more capital than the entire European AI sector raised in 2025. They did it while simultaneously releasing models that collectively hold the top five positions on global open-source leaderboards. This is not a funding cycle. This is an arms race with a product launch attached.",
    date: '2026-05-11',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200"
  },
  {
    slug: 'deepseek-73b-megaround-china-ai-funding-frenzy-2026',
    title: "DeepSeek's $7.3B Mega-Round: China's AI Funding Frenzy Hits Historic Heights",
    category: "AI",
    excerpt: "DeepSeek — the Hangzhou-based research lab that upended global AI markets in January 2025 with its shockingly efficient R1 reasoning model — is now seeking 500 billion yuan ($7.35 billion) in its...",
    date: '2026-05-10',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1551650975-87deedd944c3?w=1200"
  },
  {
    slug: 'china-agent-era-national-policy-ai-terminal-standards-anthropic-trillion-2026',
    title: "China's Agent Era Begins: National Policy Framework, AI Terminal Standards, and the Trillion-Dollar Global AI Race",
    category: "AI",
    excerpt: "Three Chinese ministries jointly issued the most comprehensive national policy framework for AI agent governance to date. AI terminal intelligence grading standards were released. Anthropic nears a $1 trillion valuation. And China's AI models processed 8 trillion tokens in a single week. May 2026 will be remembered as the month AI agents went mainstream.",
    date: '2026-05-09',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&q=80"
  },
  {
    slug: 'china-ai-infrastructure-awakening-wuwenxinqiong-deepseek-multimodal-2026',
    title: "China's AI Infrastructure Awakens: Wuwenxinqiong's $100M Bet and the Full-Stack Race to Support 8 Trillion Tokens",
    category: "AI Infrastructure",
    excerpt: "Wuwenxinqiong raised $100M+ to build China's AI-native infrastructure. DeepSeek launched multimodal capabilities. Alibaba deployed voice-first PC AI. And China's models processed 8 trillion tokens in a week—surpassing the US for the third consecutive time. The foundation layer is finally catching up to the model layer.",
    date: '2026-05-08',
    readTime: '17 min read',
    image: "https://images.unsplash.com/photo-1573164713988-8665fc963095?q=80&w=1200&auto=format&fit=crop"
  },
  {
    slug: 'doubao-charging-ai-free-era-ends-china-2026',
    title: "Doubao Starts Charging: How China's Biggest AI App Ended the Free Era — and What It Means for 345 Million Users",
    category: "AI Business",
    excerpt: "ByteDance's Doubao, China's largest AI app with 345M MAU, just launched paid tiers from $9.50 to $72/month. Here's why 120 trillion daily tokens made free unsustainable, and what this signals for the global AI industry.",
    date: '2026-05-07',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1633431871820-ca72e0da2e2b?w=1200&h=600&fit=crop"
  },
  {
    slug: 'kimi-20-billion-valuation-china-ai-token-economy',
    title: "Kimi's $20 Billion Bet: How China's AI Token Economy Is Rewriting Global Power Dynamics",
    category: "AI Industry",
    excerpt: "Kimi hits a $20 billion funding round at $200 billion valuation while China's AI token consumption surges past the US for the third time. Here's what it means for the global AI landscape.",
    date: '2026-05-07',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&q=80"
  },
  {
    slug: 'china-embodied-intelligence-revolution-2026',
    title: "China's Embodied Intelligence Revolution: How 230+ Companies and a $110 Billion Market Are Reshaping Global Robotics in 2026",
    category: "AI Infrastructure",
    excerpt: "China's embodied intelligence industry is surging from 1,800 humanoid robots shipped in 2025 to an anticipated 100,000+ in 2026, backed by $195 billion in annual funding and a supply chain that cuts costs to 50% of Western equivalents.",
    date: '2026-05-06',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80"
  },
  {
    slug: 'deepseek-v4-promo-ending-analysis',
    title: "DeepSeek V4's 75% Promo Ends May 31: What Happens Next and Why the AI Pricing War Is Just Beginning",
    category: "AI Infrastructure",
    excerpt: "DeepSeek V4 launched on April 24, 2026, with a 75% promotional discount on its flagship Pro model. Originally set to expire on May 5, the offer has been extended to May 31 — but the clock is ticking....",
    date: '2026-05-05',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800&h=400&fit=crop"
  },
  {
    slug: 'china-ai-deepfake-fraud-crisis-2026',
    title: "China's AI Deepfake Fraud Crisis: How 700,000 Annual Scams and a $40 Billion Global Threat Are Reshaping Trust in the Digital Age",
    category: "AI Safety",
    excerpt: "China's AI industry has achieved remarkable commercial success. Moonshot AI's Kimi K2.6 matches GPT-5.5 on coding benchmarks. DeepSeek V4 undercuts Western APIs by 10-30x. MiniMax filed for IPO with...",
    date: '2026-05-03',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=800&h=400&fit=crop"
  },
  {
    slug: 'china-ai-revolution-may-2026-tokens-deepseek-huawei',
    title: "China's AI Revolution: How 140 Trillion Tokens, DeepSeek V4 on Huawei Chips, and a $700B Arms Race Are Reshaping Global Technology",
    category: "AI Infrastructure",
    excerpt: "On April 24, 2026, DeepSeek quietly did something no frontier AI lab had ever attempted: it released its flagship V4 model—1.6 trillion parameters, million-token context windows, performance rivaling...",
    date: '2026-05-03',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&h=400&fit=crop"
  },
  {
    slug: 'kimi-k2-6-open-source-coding-revolution',
    title: "Kimi K2.6: How a $18B Chinese Startup Is Rewriting the Rules of Open-Source AI Coding",
    category: "AI Infrastructure",
    excerpt: "On April 20, 2026, while Silicon Valley was still processing OpenAI's GPT-5.5 launch, a Beijing-based startup quietly shipped a model that would send shockwaves through the global developer...",
    date: '2026-05-02',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&h=400&fit=crop"
  },
  {
    slug: 'china-ai-global-surge-api-traffic-empire-2026',
    title: "From Made in China to Trained in China: The Untold Story of How Chinese AI Conquered Global Developers",
    category: "AI Industry",
    excerpt: "China's technology exports have always followed a familiar playbook: manufacture hardware cheaply, sell globally, gradually move up the value chain. Smartphones took a decade. Solar panels took...",
    date: '2026-05-01',
    readTime: '17 min read',
    image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=1200&q=80"
  },
  {
    slug: 'china-ai-agent-revolution-2026-policy-market',
    title: "Inside China's AI Policy Machine: How the Politburo's 'AI+ Action' Directive Is Rewriting Procurement Law",
    category: "AI Policy",
    excerpt: "> \"The question isn't whether AI agents will replace human workers. The question is whether companies that don't deploy agents will be replaced by companies that do.\" — Industry analyst, 36Kr Summit,...",
    date: '2026-04-30',
    readTime: '17 min read',
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1200&h=600&fit=crop"
  },
  {
    slug: 'deepseek-v4-pricing-strategy-analysis',
    title: "DeepSeek V4 Pricing Strategy: How $0.14/1M Tokens Is Reshaping the Economics of Frontier AI",
    category: "AI Infrastructure",
    excerpt: "On April 24, 2026, DeepSeek released V4 — a dual-tier model family (Pro and Flash) with a pricing structure that instantly became the new global benchmark for cost-per-capability in frontier AI. The...",
    date: '2026-04-30',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=1200&q=80"
  },
  {
    slug: 'ai-compute-crunch-china-token-crisis-2026',
    title: "The Great AI Compute Crunch: How China's AI Boom Is Running Out of Tokens",
    category: "AI Infrastructure",
    excerpt: "China's AI revolution is facing an unexpected bottleneck. In April 2026, as DeepSeek launched its highly anticipated V4 model and Kimi pushed out K2.6, the nation's hottest AI companies discovered a...",
    date: '2026-04-29',
    readTime: '17 min read',
    image: "https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=800&h=400&fit=crop"
  },
  {
    slug: 'bytedance-seed-brain-drain-70-engineers',
    title: "ByteDance's AI Brain Drain: 70 Top Engineers Exit Seed Team in 12 Months",
    category: "AI Trends",
    excerpt: "Bytedance's AI Brain Drain: 70 Top Engineers Exit Seed Team in 12 Months",
    date: '2026-04-28',
    readTime: '15 min read',
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&h=400&fit=crop"
  },
  {
    slug: 'deepseek-v4-million-token-china-ai-sovereignty',
    title: "DeepSeek V4: The Million-Token API Update That Signals China's AI Sovereignty Shift",
    category: "AI Infrastructure",
    excerpt: "On April 22, 2026, Chinese developers noticed something peculiar. DeepSeek's API—previously capped at 128K context tokens—suddenly accepted prompts up to 1 million tokens. The knowledge cutoff...",
    date: '2026-04-22',
    readTime: '17 min read',
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200&h=600&fit=crop"
  },
  {
    slug: 'china-embodied-intelligence-robot-marathon-2026',
    title: "China's Embodied Intelligence Revolution: When Robots Outrun Humans — April 2026",
    category: "AI Trends",
    excerpt: "Meta Title: China's Embodied Intelligence Revolution: When Robots Outrun Humans — April 2026\nMeta Description: Honor's \"Lightning\" robot breaks human half-marathon world record in 50:26. TARS raises...",
    date: '2026-04-21',
    readTime: '18 min read',
    image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&h=400&fit=crop"
  },
  {
    slug: 'deepseek-first-funding-20-billion-valuation',
    title: "DeepSeek Breaks Its Vow: Inside the $3 Billion Funding Round That Shook China's AI World",
    category: "AI Infrastructure",
    excerpt: "On April 22, 2026, The Information broke the story that would send China's venture capital ecosystem into a frenzy: DeepSeek was finally taking external money.",
    date: '2026-04-20',
    readTime: '15 min read',
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop"
  },
  {
    slug: 'china-ai-avatar-revolution-2026',
    title: "China's AI Avatar Revolution: How 410 Million Views Signal a Global Content Creation Shift",
    category: "AI Industry",
    excerpt: "China's AI avatar market has reached an inflection point. With 410 million views on the topic \"AI数字人\" (AI Digital Humans) on Xiaohongshu alone, and a staggering 200% weekly growth rate, this isn't...",
    date: '2026-04-18',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=1200&h=600&fit=crop"
  },
  {
    slug: 'stanford-ai-index-2026-china-rise',
    title: "Stanford AI Index 2026: China's 'Parallel Run' Era Has Arrived",
    category: "AI Trends",
    excerpt: "> Alibaba ranks #3 globally and #1 in China. The performance gap between top Chinese and US AI models has narrowed to just 2.7%.",
    date: '2026-04-17',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=1200&h=600&fit=crop"
  },
  {
    slug: 'alibaba-token-hub-100b-gambit',
    title: "Alibaba's $100B Token Gambit: Inside the Alibaba Token Hub Revolution Reshaping China's AI Economy",
    category: "AI Trends",
    excerpt: "On March 16, 2026, Alibaba did something unprecedented in corporate history: it named a core business unit after a technical metric. The Alibaba Token Hub (ATH)—a name that would make most boardrooms...",
    date: '2026-04-16',
    readTime: '17 min',
    image: "https://images.unsplash.com/photo-1631914730601-6295d106b459?w=1200&h=600&fit=crop"
  },
  {
    slug: 'china-ai-agent-explosion-2025-enterprise-deployment',
    title: "China's AI Agent Explosion: How 126 Platforms and $1B+ in Enterprise Deals Are Reshaping Global Automation",
    category: "AI Trends",
    excerpt: "The Chinese AI Agent market has crossed a critical threshold in 2025. What began as experimental pilots in 2023 has evolved into a full-scale industrial deployment, with enterprises moving from...",
    date: '2026-04-15',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=1200&h=600&fit=crop"
  },
  {
    slug: 'china-ai-model-war-april-2026-week-changed-everything',
    title: "The Week That Changed Everything: China's AI Model War Intensifies in April 2026",
    category: "AI Trends",
    excerpt: "The first week of April 2026 will be remembered as the moment China's AI industry fundamentally shifted gears. What started as a typical news week quickly escalated into an unprecedented flurry of...",
    date: '2026-04-13',
    readTime: '17 min read',
    image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&q=80"
  },
  {
    slug: 'china-ai-chip-war-2026-us-sanctions',
    title: "The Great Silicon Wall: How China's AI Industry Is Defying U.S. Chip Sanctions in 2026",
    category: "AI Infrastructure",
    excerpt: "In January 2025, when the Biden administration imposed sweeping restrictions on AI chip exports to China, the consensus in Silicon Valley was clear: Chinese AI development would slow dramatically....",
    date: '2026-04-12',
    readTime: '17 min read',
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&h=600&fit=crop"
  },
  {
    slug: 'china-ai-model-wars-april-2026',
    title: "China's AI Model Wars: How Alibaba, ByteDance, and MiniMax Are Reshaping Global AI Competition in April 2026",
    category: "AI Trends",
    excerpt: "April 1-10, 2026 will be remembered as the moment China's AI industry shifted from \"fast follower\" to \"global leader.\" In just ten days, domestic tech giants unleashed a barrage of innovations that...",
    date: '2026-04-11',
    readTime: '18 min read',
    image: "https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=1200&h=600&fit=crop"
  },
  {
    slug: 'modelbest-edge-ai-unicorn-2026',
    title: "ModelBest Becomes Unicorn: How Tsinghua's Edge AI Pioneer Is Reshaping On-Device Intelligence",
    category: "AI Trends",
    excerpt: "A quiet revolution in artificial intelligence is happening on the smallest screens. While tech giants battle for cloud dominance, ModelBest—a Tsinghua University spinoff barely three years old—has...",
    date: '2026-04-10',
    readTime: '17 min',
    image: "https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=1200&h=600&fit=crop"
  },
  {
    slug: 'ai-interview-coaching-china-2025',
    title: "The AI Interview Coach Phenomenon: How Chinese Graduates Are Using AI to Crack the Job Market",
    category: "AI Trends",
    excerpt: "China's job market has become a battleground for millions of fresh graduates, and a surprising new weapon has emerged: AI interview coaches. In the past week alone, searches for \"AI interview...",
    date: '2026-04-08',
    readTime: '16 min',
    image: "https://images.unsplash.com/photo-1579621970563-eefec7560ff3e?w=1200&h=600&fit=crop"
  },
  {
    slug: 'china-ai-token-surge-gen-z',
    title: "China's AI Overtake: 31% Surge in Token Usage Signals Global Power Shift",
    category: "AI Trends",
    excerpt: "China's AI Overtake: 31% Surge in Token Usage Signals Global Power Shift",
    date: '2026-04-07',
    readTime: '17 min read',
    image: "https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=800&h=400&fit=crop"
  },
  {
    slug: 'china-ai-avatar-revolution-2025',
    title: "China's AI Avatar Revolution: 410M Views Transformed Content Creation Forever",
    category: "AI Trends",
    excerpt: "Something extraordinary is happening on Chinese social media. In the first week of April 2026, the topic \"AI Digital Human\" (AI数字人) on Xiaohongshu (China's Instagram-equivalent) accumulated 410...",
    date: '2026-04-05',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1551434678-e076c223a692?w=1200&h=600&fit=crop"
  },
  {
    slug: 'china-ai-digital-human-revolution',
    title: "China's AI Digital Human Revolution: 80,000 Virtual Avatars Reshaping Content",
    category: "AI Applications",
    excerpt: "The creator economy in China has reached an inflection point. A single hashtag on Xiaohongshu—\"AI数字人\" (AI Digital Human)—has accumulated 410 million views with a staggering +200% growth in just one...",
    date: '2026-04-05',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&q=80"
  },
  {
    slug: 'doubao-12-trillion-token-explosion',
    title: "Doubao's 12 Trillion Token Explosion: How ByteDance Is Quietly Winning the Global AI Race",
    category: "AI Infrastructure",
    excerpt: "On April 2, 2026, while Silicon Valley was still digesting the latest GPT-5 rumors, a single announcement from Wuhan, China sent shockwaves through the global AI industry.",
    date: '2026-04-04',
    readTime: '10 min read',
    image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=1200"
  },
  {
    slug: 'stepfun-terminal-ai-revolution',
    title: "StepFun's $7 Billion Bet: How China's AI Unicorn Is Winning the Terminal Race",
    category: "AI Infrastructure",
    excerpt: "On January 26, 2026, while most of the tech world was still digesting DeepSeek's open-source strategy, another Shanghai-based AI company quietly dropped a bombshell that would reshape the competitive...",
    date: '2026-04-03',
    readTime: '10 min read',
    image: "https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=1200"
  },
  {
    slug: 'ai-thesis-writing-china',
    title: "AI Thesis Writing Explodes: How 12 Million Chinese Students Are Rewriting Academic Rules",
    category: "AI Chatbots",
    excerpt: "In the months leading up to China's 2026 graduation season, a remarkable trend erupted across Chinese social media: \"AI thesis writing\" (AI写论文).",
    date: '2026-04-02',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=800&h=400&fit=crop"
  },
  {
    slug: 'doubao-bytedance',
    title: "ByteDance Doubao: The 200 Million User AI Assistant Reshaping Content Creation",
    category: "AI Chatbots",
    excerpt: "While Baidu's Wenxin Yiyan dominates search integration and DeepSeek captures the technical elite, ByteDance's Doubao has carved out a different kingdom: 200 million monthly active users who create,...",
    date: '2026-04-02',
    readTime: '15 min read',
    image: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&h=400&fit=crop"
  },
  {
    slug: 'bytedance-ai-gamble-gpu-kingpin-profit-drop',
    title: "ByteDance's AI Obsession: How a 70% Profit Plunge Turned a Social Media Giant Into China's GPU Kingpin",
    category: "AI Trends",
    excerpt: "On April 20, 2026, Securities Times dropped a bombshell that rippled through China's tech ecosystem: ByteDance's 2025 net profit had collapsed by more than 70% compared to the previous year. The...",
    date: '2026-04-01',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&h=400&fit=crop"
  },
  {
    slug: 'china-ai-april-infrastructure-2026',
    title: "China's AI Revolution: Education Reform, National Standards, and Ecosystem Breakthroughs in April 2026",
    category: "AI Infrastructure",
    excerpt: "China's AI Revolution: Education Reform, National Standards, and Ecosystem Breakthroughs in April 2026",
    date: '2026-04-01',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1685558589023-3297b012d8bc?w=1200&h=600&fit=crop"
  },
  {
    slug: 'minimax-ipo-212-million-users-ai-companion-empire',
    title: "MiniMax Files for IPO: How China's AI Companion Empire Built 212 Million Users and Challenged the Global Social Landscape",
    category: "AI Robotics",
    excerpt: "MiniMax Files for IPO: How China's AI Companion Empire Built 212 Million Users and Challenged the Global Social Landscape",
    date: '2026-04-01',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=1200&h=600&fit=crop"
  },
  {
    slug: 'tars-embodied-intelligence-455-million-brain-club',
    title: "Tars Raises $455M: How China's 'Robot Brain' Startup Cracked the Embodied Intelligence Code",
    category: "AI Robotics",
    excerpt: "Tars Raises $455M: How China's \"Robot Brain\" Startup Cracked the Embodied Intelligence Code",
    date: '2026-04-01',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1567789884554-0b844b597180?w=1200&h=600&fit=crop"
  },
  {
    slug: 'tongyi-qianwen-alibaba',
    title: "Alibaba Tongyi Qianwen: Enterprise AI Powerhouse",
    category: "AI Chatbots",
    excerpt: "While Baidu captured consumer mindshare and DeepSeek shocked the industry with cost efficiency, Alibaba's Tongyi Qianwen has quietly built the most comprehensive enterprise AI platform in China. With...",
    date: '2026-04-01',
    readTime: '14 min read',
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=400&fit=crop"
  },
  {
    slug: 'wenxin-yiyan-baidu',
    title: "Baidu Wenxin Yiyan: The 300 Million User AI Assistant",
    category: "AI Chatbots",
    excerpt: "When international headlines celebrate DeepSeek's cost efficiency and Kimi's technical innovations, Baidu's Wenxin Yiyan has quietly achieved something equally remarkable: 300 million monthly active...",
    date: '2026-04-01',
    readTime: '14 min read',
    image: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=800&h=400&fit=crop"
  },
  {
    slug: 'ai-video-tools-china',
    title: "Chinese AI Video Generation: Kling, Vidu, Hailuo vs Sora Technical Comparison",
    category: "AI Video",
    excerpt: "While OpenAI's Sora captured global attention with its demonstration videos, Chinese companies have been quietly building video generation tools that are already in production use. Kling, Vidu, and...",
    date: '2026-03-31',
    readTime: '15 min read',
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&h=400&fit=crop"
  },
  {
    slug: 'chinese-ai-index-2026',
    title: "Chinese AI Index: 103 Companies Tracking",
    category: "Market Intelligence",
    excerpt: "The Chinese AI ecosystem has reached an inflection point. With over 103 significant companies spanning foundation models, application layers, and infrastructure, China's AI sector is now a global...",
    date: '2026-03-31',
    readTime: '12 min read',
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=400&fit=crop"
  },
  {
    slug: 'deepseek-v3-deep-dive',
    title: "DeepSeek-V3: The $5.6M Training Run",
    category: "Technical Analysis",
    excerpt: "DeepSeek-V3 represents one of the most significant efficiency breakthroughs in AI history. Training a model competitive with GPT-4 for just $5.6 million challenges fundamental assumptions about the...",
    date: '2026-03-31',
    readTime: '15 min read',
    image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&h=400&fit=crop"
  },
  {
    slug: 'deepseek-vs-chatgpt',
    title: "DeepSeek vs ChatGPT: Complete Comparison",
    category: "AI Chatbots",
    excerpt: "Choosing between DeepSeek and ChatGPT is no longer obvious. This comprehensive comparison helps you decide which AI assistant fits your needs.",
    date: '2026-03-31',
    readTime: '10 min read',
    image: "https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=800&h=400&fit=crop"
  },
  {
    slug: 'minimax-talkie',
    title: "MiniMax: The 212 Million User AI Companion Empire Built on Digital Intimacy",
    category: "AI Chatbots",
    excerpt: "While ByteDance's Doubao dominates content creation and DeepSeek captures the technical elite, MiniMax has built something arguably more intimate: 212 million users who have formed emotional bonds...",
    date: '2026-03-31',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1764664281860-c5725fafa634?w=800&h=400&fit=crop"
  },
  {
    slug: 'chinese-ai-landscape',
    title: "The Rise of Chinese AI: Complete Ecosystem Map (Foundation to Application)",
    category: "Market Intelligence",
    excerpt: "China's AI ecosystem has evolved from a fragmented collection of research labs into a comprehensive industrial stack that rivals Silicon Valley. Understanding this landscape—from domestic chip...",
    date: '2026-03-30',
    readTime: '20 min read',
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&h=400&fit=crop"
  },
  {
    slug: 'kimi-2m-context',
    title: "Kimi K2.5 Technical Analysis: 1 Trillion Parameters, 256K Context, Agent Swarms",
    category: "AI Chatbots",
    excerpt: "When Cursor announced that Composer 2.0 was built on Kimi K2.5 rather than GPT-4 or Claude, the message was clear: Chinese foundation models had reached parity with Western alternatives. But Kimi...",
    date: '2026-03-30',
    readTime: '16 min read',
    image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&h=400&fit=crop"
  }
]

export { allPosts }
